In [1]:
# 목표 : flourish 사이틀 활용해서 동적인 데이터 시각화 차트 제작
# 준비물 : 국가명, 국기이미지url, 날짜별 확진자수
# 해야할 것 : pandas 라이브러리 모듈 활용 > 필요한데이터 추출, 불필요한 데이터 삭제, 데이터 형태 타입 통일화, 결측치 (제거, 대체), 현재 날짜에 따른 데이터를 하나로 묶어 (병합)

In [1]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [2]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}03-01-2020.csv", encoding="utf-8-sig")
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140

In [3]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN

In [7]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

try :
    doc = doc[["Province_State", "Country_Region", "Confirmed"]]
except :
    doc = doc[["Province/State", "Country/Region", "Confirmed"]]
    doc.columns = ["Province_State", "Country_Region", "Confirmed"]

doc = doc.dropna(subset=["Confirmed"])
doc = doc.astype({"Confirmed": "int64"})

doc.head()

# https://public.flourish.studio/country-flags/svg/ca.svg

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China          1
1        Beijing  Mainland China         14
2      Chongqing  Mainland China          6
3         Fujian  Mainland China          1
5      Guangdong  Mainland China         26

In [8]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [9]:
import pandas as pd

country_info = pd.read_csv("COVID-19-master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv", encoding="utf-8-sig")
country_info.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Population
0,4,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.93911,67.709953,Afghanistan,38928341.0
1,8,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.15330,20.168300,Albania,2877800.0
2,10,AQ,ATA,10.0,NaN,NaN,NaN,Antarctica,-71.94990,23.347000,Antarctica,NaN
3,12,DZ,DZA,12.0,NaN,NaN,NaN,Algeria,28.03390,1.659600,Algeria,43851043.0
4,20,AD,AND,20.0,NaN,NaN,NaN,Andorra,42.50630,1.521800,Andorra,77265.0

In [10]:
test_df = pd.merge(doc, country_info, on="Country_Region", how="left")
test_df.shape

(7591775, 23)

In [11]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7591775 entries, 0 to 7591774
Data columns (total 23 columns):
 #   Column            Dtype
---  ------            -----
 0   FIPS_x            float64
 1   Admin2_x          object
 2   Province_State_x  object
 3   Country_Region    object
 4   Last_Update       object
 5   Lat_x             float64
 6   Long__x           float64
 7   Confirmed         int64
 8   Deaths            int64
 9   Recovered         int64
 10  Active            int64
 11  Combined_Key_x    object
 12  UID               int64
 13  iso2              object
 14  iso3              object
 15  code3             float64
 16  FIPS_y            float64
 17  Admin2_y          object
 18  Province_State_y  object
 19  Lat_y             float64
 20  Long__y           float64
 21  Combined_Key_y    object
 22  Population        float64
dtypes: float64(8), int64(5), object(10)
memory usage: 1.3+ GB

In [13]:
test_df.isnull().sum()

FIPS_x              197269
Admin2_x             27049
Province_State_x       804
Country_Region           0
Last_Update              0
Lat_x                 3488
Long__x               3488
Confirmed                0
Deaths                   0
Recovered                0
Active                   0
Combined_Key_x           0
UID                      0
iso2                     5
iso3                     4
code3                    4
FIPS_y               52223
Admin2_y            143571
Province_State_y      2522
Lat_y               265276
Long__y             265276
Combined_Key_y           0
Population          265279
dtype: int64

In [15]:
nan_rows = test_df[test_df["iso2"].isnull()]
nan_rows.head()

,FIPS_x,Admin2_x,Province_State_x,Country_Region,Last_Update,Lat_x,Long__x,Confirmed,Deaths,Recovered,...,iso2,iso3,code3,FIPS_y,Admin2_y,Province_State_y,Lat_y,Long__y,Combined_Key_y,Population
7590572,NaN,NaN,NaN,Diamond Princess,2020-04-01 21:58:34,0.0000,0.0000,712,11,603,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Diamond Princess,NaN
7590762,NaN,NaN,NaN,MS Zaandam,2020-04-01 21:58:34,0.0000,0.0000,9,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MS Zaandam,NaN
7590854,NaN,NaN,NaN,Namibia,2020-04-01 21:58:34,-22.9576,18.4904,14,0,2,...,NaN,NAM,516.0,NaN,NaN,NaN,-22.9576,18.4904,Namibia,2540916.0
7591290,NaN,NaN,NaN,Summer Olympics 2020,2020-04-01 21:58:49,35.6491,139.7737,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,35.6491,139.7737,Summer Olympics 2020,NaN
7591598,NaN,NaN,NaN,Winter Olympics 2022,2020-04-01 21:58:49,39.9042,116.4074,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,39.9042,116.4074,Winter Olympics 2022,NaN

In [16]:
test_df = test_df.dropna(subset=["iso2"])

In [17]:
test_df.isnull().sum()

FIPS_x              197264
Admin2_x             27044
Province_State_x       799
Country_Region           0
Last_Update              0
Lat_x                 3488
Long__x               3488
Confirmed                0
Deaths                   0
Recovered                0
Active                   0
Combined_Key_x           0
UID                      0
iso2                     0
iso3                     0
code3                    0
FIPS_y               52218
Admin2_y            143566
Province_State_y      2517
Lat_y               265274
Long__y             265274
Combined_Key_y           0
Population          265275
dtype: int64

In [ ]:
# 반복실행을 통해서 위에서 정의한 연산처리구문을 하나의 그룹을 설정 (함수)
# apply() 함수 : 데이터프레임 내 특정 컬럼값을 찾아서 변경해주는 함수

In [18]:
df = pd.DataFrame({
    "영어": [60, 70],
    "수학": [100, 50]
}, index=["Dave", "David"])

df

       영어   수학
Dave   60  100
David  70   50

In [24]:
def func(df_data) :
    print(type(df_data)) 
    print(df_data.index)
    print(df_data.values)
    return df_data

In [26]:
df_func = df.apply(func, axis=0) # 콜백 함수 관계

<class 'pandas.core.series.Series'>
Index(['Dave', 'David'], dtype='object')
[60 70]
<class 'pandas.core.series.Series'>
Index(['Dave', 'David'], dtype='object')
[100  50]

In [27]:
df_func = df.apply(func, axis=1)

<class 'pandas.core.series.Series'>
Index(['영어', '수학'], dtype='object')
[ 60 100]
<class 'pandas.core.series.Series'>
Index(['영어', '수학'], dtype='object')
[70 50]

In [28]:
def func(df_data) :
    df_data["영어"] = 80
    return df_data

In [29]:
df_func = df.apply(func, axis=1)

In [30]:
df_func

       영어   수학
Dave   80  100
David  80   50

In [31]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

try :
    doc = doc[["Province_State", "Country_Region", "Confirmed"]]
except :
    doc = doc[["Province/State", "Country/Region", "Confirmed"]]
    doc.columns = ["Province_State", "Country_Region", "Confirmed"]

doc = doc.dropna(subset=["Confirmed"])
doc = doc.astype({"Confirmed": "int64"})

doc.head()

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China          1
1        Beijing  Mainland China         14
2      Chongqing  Mainland China          6
3         Fujian  Mainland China          1
5      Guangdong  Mainland China         26

In [34]:
import json

with open("COVID-19-master/csse_covid_19_data/country_convert.json", "r", encoding="utf-8-sig") as json_file :
    json_data = json.load(json_file)
    print(json_data)
    print(json_data.keys())

{'Mainland China': 'China', 'Macau': 'China', 'South Korea': 'Korea, South', 'Aruba': 'Netherlands', ' Azerbaijan': 'Azerbaijan', 'Bahamas, The': 'Bahamas', 'Cape Verde': 'Cabo Verde', 'Cayman Islands': 'United Kingdom', 'Channel Islands': 'United Kingdom', 'Curacao': 'Netherlands', 'Czech Republic': 'Czechia', 'East Timor': 'Timor-Leste', 'Faroe Islands': 'Denmark', 'French Guiana': 'France', 'Gambia, The': 'Gambia', 'Gibraltar': 'United Kingdom', 'Greenland': 'Denmark', 'Guadeloupe': 'France', 'Guam': 'US', 'Guernsey': 'US', 'Hong Kong': 'China', 'Hong Kong SAR': 'China', 'Iran (Islamic Republic of)': 'Iran', 'Ivory Coast': "Cote d'Ivoire", 'Jersey': 'US', 'Macao SAR': 'China', 'Martinique': 'France', 'Mayotte': 'France', 'North Ireland': 'United Kingdom', 'Palestine': 'West Bank and Gaza', 'Puerto Rico': 'US', 'Republic of Ireland': 'Ireland', 'Republic of Korea': 'Korea, South', 'Republic of Moldova': 'Moldova', 'Republic of the Congo': 'Congo (Brazzaville)', 'Reunion': 'France', 'Russian Federation': 'Russia', 'Saint Barthelemy': 'France', 'Saint Martin': 'France', 'St. Martin': 'US', 'Taipei and environs': 'Taiwan', 'The Bahamas': 'Bahamas', 'The Gambia': 'Gambia', 'UK': 'United Kingdom', 'Vatican City': 'Holy See', 'Viet Nam': 'Vietnam', 'occupied Palestinian territory': 'West Bank and Gaza', 'Taiwan*': 'Taiwan', 'Malawi': 'France', 'South Sudan': 'Sudan', 'Western Sahara': 'Morocco', 'Namibia': 'Namibia'}
dict_keys(['Mainland China', 'Macau', 'South Korea', 'Aruba', ' Azerbaijan', 'Bahamas, The', 'Cape Verde', 'Cayman Islands', 'Channel Islands', 'Curacao', 'Czech Republic', 'East Timor', 'Faroe Islands', 'French Guiana', 'Gambia, The', 'Gibraltar', 'Greenland', 'Guadeloupe', 'Guam', 'Guernsey', 'Hong Kong', 'Hong Kong SAR', 'Iran (Islamic Republic of)', 'Ivory Coast', 'Jersey', 'Macao SAR', 'Martinique', 'Mayotte', 'North Ireland', 'Palestine', 'Puerto Rico', 'Republic of Ireland', 'Republic of Korea', 'Republic of Moldova', 'Republic of the Congo', 'Reunion', 'Russian Federation', 'Saint Barthelemy', 'Saint Martin', 'St. Martin', 'Taipei and environs', 'The Bahamas', 'The Gambia', 'UK', 'Vatican City', 'Viet Nam', 'occupied Palestinian territory', 'Taiwan*', 'Malawi', 'South Sudan', 'Western Sahara', 'Namibia'])

In [35]:
def func(row) :
    if row["Country_Region"] in json_data :
        row["Country_Region"] = json_data[row["Country_Region"]]
    return row

In [36]:
doc = doc.apply(func, axis=1)
doc.head()

  Province_State Country_Region  Confirmed
0          Anhui          China          1
1        Beijing          China         14
2      Chongqing          China          6
3         Fujian          China          1
5      Guangdong          China         26

In [37]:
# 동적 정보 시각화 차트 생성을 위한 전처리

# 1. 동일한 컬럼명 통일
# 2. 확진자수 = 결측치 제거
# 3. 확진자수 = 타입변경
# 4. 국가이름 통일 = 국가이름에 따른 1개의 국기 매칭
# 5. 코로나 확진 데이터 파일명 = 일괄수정

In [42]:
data = "01-22-2020.csv" # 1/22/2020 필드명 -> 각 국가마다 확진자수

date_column = data.split(".")[0].lstrip("0").replace("-", "/") # ["01-22-2020", "csv"]

In [43]:
date_column

'1/22/2020'

In [44]:
doc

      Province_State  Country_Region  Confirmed
0              Anhui           China          1
1            Beijing           China         14
2          Chongqing           China          6
3             Fujian           China          1
5          Guangdong           China         26
..               ...             ...        ...
71           Unknown  United Kingdom          0
72               NaN           Nauru          0
73              Niue     New Zealand          0
74               NaN          Tuvalu          0
75  Pitcairn Islands  United Kingdom          0

[66 rows x 3 columns]

In [46]:
doc.columns = ['Province_State', 'Country_Region', date_column]

In [47]:
doc.columns

Index(['Province_State', 'Country_Region', '1/22/2020'], dtype='object')

In [48]:
doc.head()

  Province_State Country_Region  1/22/2020
0          Anhui          China          1
1        Beijing          China         14
2      Chongqing          China          6
3         Fujian          China          1
5      Guangdong          China         26

In [54]:
df = pd.DataFrame({
    "성별": ["남", "남", "남"],
    "이름": ["David", "Dave", "Dave"],
    "수학": [100, 50, 80],
    "국어": [80, 70, 50]
})

df

  성별     이름   수학  국어
0  남  David  100  80
1  남   Dave   50  70
2  남   Dave   80  50

In [53]:
selected_columns = ["이름", "수학", "국어"]
df = df[selected_columns]
df.groupby("이름").mean() # 평균 수치값 계산 -> 사전, 정수 형태의 값으로 변환! | 정수 형태의 값만 따로 선별해서 연산처리!

          수학    국어
이름
Dave    65.0  60.0
David  100.0  80.0

In [55]:
df.groupby("이름").sum() # 평균 -> 무조건, 수치형 데이터만 연산 가능, 더하기 -> 비수치형 데이터 가능!

       성별   수학   국어
이름
Dave   남남  130  120
David   남  100   80

In [56]:
# 국가별 총 확진자 수!!! 확찐자~!!

import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

try :
    doc = doc[["Province_State", "Country_Region", "Confirmed"]]
except :
    doc = doc[["Province/State", "Country/Region", "Confirmed"]]
    doc.columns = ["Province_State", "Country_Region", "Confirmed"]

doc = doc.dropna(subset=["Confirmed"])
doc = doc.astype({"Confirmed": "int64"})

doc.head()

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China          1
1        Beijing  Mainland China         14
2      Chongqing  Mainland China          6
3         Fujian  Mainland China          1
5      Guangdong  Mainland China         26

In [57]:
doc.groupby("Country_Region").sum()

,Province_State,Confirmed
Country_Region,,
Antarctica,0,0
Japan,0,2
Kiribati,0,0
"Korea, North",0,0
Macau,Macau,1
Mainland China,AnhuiBeijingChongqingFujianGuangdongGuangxiGui...,547
Malaysia,JohorKedahKelantanMelakaNegeri SembilanPahangP...,0
Nauru,0,0
New Zealand,Cook IslandsNiue,0
Palau,0,0
South Korea,0,1
Summer Olympics 2020,0,0
Taiwan,Taiwan,1
Thailand,0,4
Tonga,0,0
Tuvalu,0,0
US,Washington,1
Ukraine,Unknown,0
United Kingdom,JerseyGuernseyEnglandNorthern IrelandScotlandW...,0
Winter Olympics 2022,0,0

# 우리가 동적인 데이터 시각화 자료 제작을 위해서 처리해야하는 목록

1. csv 파일 로드
2. "Country_Region", "Confirmed" 2개 컬럼 가져오기
3. "Confirmed" 에서 데이터가 없는 행 제거하기 (null값 제거)
4. "Country_Region" 에서 국가명을 일관성있게 변경하기 (json 활용)
5. "Confirmed" 의 데이터 타입을 int64(정수)로 변경하기
6. "Country_Region"을 기준으로 그룹화하기 (group by)
7. 파일명을 기반으로 날짜 문자열 패턴화하기, "Confirmed" 컬럼명 변경

In [59]:
import pandas as pd
import json

with open("COVID-19-master/csse_covid_19_data/country_convert.json", "r", encoding="utf-8-sig") as json_file :
    json_data = json.load(json_file)

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"

def country_name_convert(row) :
    if row["Country_Region"] in json_data :
        return json_data[row["Country_Region"]]
    return row["Country_Region"]
    

def create_dataframe(filename) :
    doc = pd.read_csv(f"{PATH}{filename}", encoding="utf-8-sig")
    
    try :
        doc = doc[["Country_Region", "Confirmed"]]
    except :
        doc = doc[["Country/Region", "Confirmed"]]
        doc.columns = ["Country_Region", "Confirmed"]
    
    doc = doc.dropna(subset=["Confirmed"])
    doc["Country_Region"] = doc.apply(country_name_convert, axis=1)
    doc = doc.astype({"Confirmed": "int64"})
    doc = doc.groupby("Country_Region").sum()

    date_column = filename.split(".")[0].lstrip("0").replace("-", "/")
    doc.columns = [date_column]
    return doc

In [64]:
doc1 = create_dataframe("01-22-2020.csv")
doc2 = create_dataframe("04-01-2020.csv")

In [65]:
doc2.shape

(190, 1)

In [66]:
doc2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 190 entries, Afghanistan to Zimbabwe
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   4/01/2020  190 non-null    int64
dtypes: int64(1)
memory usage: 3.0+ KB

In [67]:
doc2.head()

                4/01/2020
Country_Region
Afghanistan           192
Albania               259
Algeria               847
Andorra               390
Angola                  8

In [68]:
doc = pd.merge(doc1, doc2, how="outer", left_index=True, right_index=True)
doc.head()

                1/22/2020  4/01/2020
Country_Region
Afghanistan           NaN        192
Albania               NaN        259
Algeria               NaN        847
Andorra               NaN        390
Angola                NaN          8

In [69]:
doc = doc.fillna(0)
doc

                      1/22/2020  4/01/2020
Country_Region
Afghanistan                 0.0        192
Albania                     0.0        259
Algeria                     0.0        847
Andorra                     0.0        390
Angola                      0.0          8
...                         ...        ...
Vietnam                     0.0        218
West Bank and Gaza          0.0        134
Winter Olympics 2022        0.0          0
Zambia                      0.0         36
Zimbabwe                    0.0          8

[190 rows x 2 columns]

In [74]:
import os

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"

# 구조분해할당 문법

# file_list = os.listdir(PATH)
# csv_list = list()

file_list, csv_list = os.listdir(PATH), list()

for file in file_list :
    if file.split(".")[-1] == "csv" :
        csv_list.append(file)

print(csv_list)

['01-21-2022.csv', '02-26-2020.csv', '01-20-2022.csv', '02-27-2020.csv', '07-04-2021.csv', '07-05-2021.csv', '02-12-2022.csv', '02-13-2022.csv', '12-31-2021.csv', '12-30-2021.csv', '11-02-2021.csv', '11-03-2021.csv', '08-21-2021.csv', '08-20-2021.csv', '11-09-2022.csv', '11-08-2022.csv', '03-25-2021.csv', '03-24-2021.csv', '06-07-2020.csv', '06-06-2020.csv', '05-01-2022.csv', '02-19-2021.csv', '10-01-2020.csv', '02-18-2021.csv', '09-22-2020.csv', '09-23-2020.csv', '04-08-2020.csv', '09-16-2022.csv', '09-17-2022.csv', '04-09-2020.csv', '04-09-2021.csv', '04-08-2021.csv', '09-23-2021.csv', '09-22-2021.csv', '02-18-2020.csv', '02-19-2020.csv', '10-01-2021.csv', '06-06-2021.csv', '06-07-2021.csv', '03-24-2020.csv', '03-25-2020.csv', '03-10-2022.csv', '03-11-2022.csv', '08-20-2020.csv', '08-21-2020.csv', '12-04-2022.csv', '11-03-2020.csv', '12-05-2022.csv', '11-02-2020.csv', '08-14-2022.csv', '08-15-2022.csv', '12-30-2020.csv', '12-31-2020.csv', '07-31-2022.csv', '09-28-2022.csv', '09-29-2022.csv', '07-30-2022.csv', '02-13-2023.csv', '01-14-2021.csv', '02-12-2023.csv', '01-15-2021.csv', '07-05-2020.csv', '04-02-2022.csv', '07-04-2020.csv', '04-03-2022.csv', '02-27-2021.csv', '01-20-2023.csv', '02-26-2021.csv', '01-21-2023.csv', '01-20-2021.csv', '02-27-2023.csv', '01-21-2021.csv', '02-26-2023.csv', '04-02-2020.csv', '07-05-2022.csv', '04-03-2020.csv', '07-04-2022.csv', '01-14-2023.csv', '02-13-2021.csv', '01-15-2023.csv', '02-12-2021.csv', '09-28-2020.csv', '07-31-2020.csv', '07-30-2020.csv', '09-29-2020.csv', '12-30-2022.csv', '12-31-2022.csv', '08-14-2020.csv', '08-15-2020.csv', '11-03-2022.csv', '12-04-2020.csv', '11-02-2022.csv', '12-05-2020.csv', '08-20-2022.csv', '08-21-2022.csv', '11-08-2021.csv', '03-10-2020.csv', '11-09-2021.csv', '03-11-2020.csv', '03-24-2022.csv', '03-25-2022.csv', '05-01-2021.csv', '02-18-2022.csv', '02-19-2022.csv', '09-17-2021.csv', '09-16-2021.csv', '09-16-2020.csv', '04-08-2022.csv', '04-09-2022.csv', '09-17-2020.csv', '09-22-2022.csv', '09-23-2022.csv', '10-01-2022.csv', '02-19-2023.csv', '02-18-2023.csv', '06-07-2022.csv', '05-01-2020.csv', '06-06-2022.csv', '11-09-2020.csv', '03-11-2021.csv', '11-08-2020.csv', '03-10-2021.csv', '12-05-2021.csv', '12-04-2021.csv', '08-15-2021.csv', '08-14-2021.csv', '09-29-2021.csv', '07-30-2021.csv', '07-31-2021.csv', '09-28-2021.csv', '02-12-2020.csv', '01-15-2022.csv', '02-13-2020.csv', '01-14-2022.csv', '04-03-2021.csv', '04-02-2021.csv', '02-26-2022.csv', '02-27-2022.csv', '01-09-2023.csv', '10-16-2020.csv', '01-08-2023.csv', '10-17-2020.csv', '07-18-2022.csv', '09-01-2022.csv', '07-19-2022.csv', '10-22-2022.csv', '10-23-2022.csv', '05-23-2020.csv', '06-24-2022.csv', '05-22-2020.csv', '06-25-2022.csv', '03-06-2023.csv', '12-19-2020.csv', '03-07-2023.csv', '12-18-2020.csv', '08-09-2020.csv', '05-17-2022.csv', '06-10-2020.csv', '05-16-2022.csv', '06-11-2020.csv', '08-08-2020.csv', '12-26-2021.csv', '12-27-2021.csv', '11-15-2021.csv', '11-14-2021.csv', '07-13-2021.csv', '07-12-2021.csv', '10-29-2021.csv', '10-28-2021.csv', '04-20-2021.csv', '04-21-2021.csv', '02-05-2022.csv', '02-04-2022.csv', '01-03-2021.csv', '02-04-2023.csv', '01-02-2021.csv', '02-05-2023.csv', '04-21-2020.csv', '07-26-2022.csv', '04-20-2020.csv', '07-27-2022.csv', '10-28-2020.csv', '10-29-2020.csv', '04-15-2022.csv', '07-12-2020.csv', '04-14-2022.csv', '07-13-2020.csv', '11-14-2020.csv', '12-13-2022.csv', '11-15-2020.csv', '12-12-2022.csv', '05-29-2022.csv', '05-28-2022.csv', '11-20-2022.csv', '12-27-2020.csv', '11-21-2022.csv', '12-26-2020.csv', '08-03-2022.csv', '08-02-2022.csv', '08-08-2021.csv', '06-11-2021.csv', '06-10-2021.csv', '08-09-2021.csv', '03-07-2022.csv', '12-18-2021.csv', '03-06-2022.csv', '12-19-2021.csv', '05-22-2021.csv', '05-23-2021.csv', '01-08-2022.csv', '10-17-2021.csv', '01-09-2022.csv', '10-16-2021.csv', '07-19-2021.csv', '07-18-2021.csv', '09-01-2021.csv', '10-23-2021.csv', '10-22-2021.csv', '06-25-2021.csv', '06-24-2021.csv', '03-07-2020.csv', '03-06-2020.csv', '05-16-2021.csv', '05-17-2021.csv', '08-03-2020.csv', '08-02-2020.csv', '12-27-2022.csv', '11-20-2020.csv', '12-26-2022.csv', '11-21-2020.csv', '05-29-2020.csv', '05-28-2020.csv', '12-13-2020.csv', '11-14-2022.csv', '12-12-2020.csv', '11-15-2022.csv', '07-12-2022.csv', '04-15-2020.csv', '07-13-2022.csv', '04-14-2020.csv', '10-28-2022.csv', '10-29-2022.csv', '07-26-2020.csv', '04-21-2022.csv', '07-27-2020.csv', '04-20-2022.csv', '02-04-2021.csv', '01-03-2023.csv', '02-05-2021.csv', '01-02-2023.csv', '01-02-2022.csv', '02-05-2020.csv', '01-03-2022.csv', '02-04-2020.csv', '07-27-2021.csv', '07-26-2021.csv', '04-14-2021.csv', '04-15-2021.csv', '12-12-2021.csv', '12-13-2021.csv', '05-28-2021.csv', '05-29-2021.csv', '11-21-2021.csv', '11-20-2021.csv', '08-02-2021.csv', '08-03-2021.csv', '06-10-2022.csv', '05-17-2020.csv', '08-09-2022.csv', '08-08-2022.csv', '06-11-2022.csv', '05-16-2020.csv', '12-19-2022.csv', '03-06-2021.csv', '12-18-2022.csv', '03-07-2021.csv', '06-24-2020.csv', '05-23-2022.csv', '06-25-2020.csv', '05-22-2022.csv', '10-22-2020.csv', '10-23-2020.csv', '09-01-2020.csv', '07-18-2020.csv', '07-19-2020.csv', '10-16-2022.csv', '01-09-2021.csv', '10-17-2022.csv', '01-08-2021.csv', '06-23-2022.csv', '05-24-2020.csv', '06-22-2022.csv', '05-25-2020.csv', '03-01-2023.csv', '11-19-2022.csv', '11-18-2022.csv', '06-17-2020.csv', '05-10-2022.csv', '06-16-2020.csv', '05-11-2022.csv', '02-09-2021.csv', '10-11-2020.csv', '02-08-2021.csv', '10-10-2020.csv', '09-06-2022.csv', '04-18-2020.csv', '04-19-2020.csv', '09-07-2022.csv', '10-25-2022.csv', '10-24-2022.csv', '07-14-2021.csv', '07-15-2021.csv', '01-31-2022.csv', '01-30-2022.csv', '04-27-2021.csv', '04-26-2021.csv', '02-02-2022.csv', '02-03-2022.csv', '12-21-2021.csv', '12-20-2021.csv', '06-28-2021.csv', '08-31-2021.csv', '08-30-2021.csv', '06-29-2021.csv', '11-12-2021.csv', '11-13-2021.csv', '12-14-2022.csv', '11-13-2020.csv', '12-15-2022.csv', '11-12-2020.csv', '06-29-2020.csv', '08-30-2020.csv', '08-31-2020.csv', '06-28-2020.csv', '12-20-2020.csv', '11-27-2022.csv', '12-21-2020.csv', '11-26-2022.csv', '08-04-2022.csv', '08-05-2022.csv', '02-03-2023.csv', '01-04-2021.csv', '02-02-2023.csv', '01-05-2021.csv', '07-21-2022.csv', '04-26-2020.csv', '07-20-2022.csv', '04-27-2020.csv', '01-30-2023.csv', '01-31-2023.csv', '07-15-2020.csv', '04-12-2022.csv', '07-14-2020.csv', '04-13-2022.csv', '04-19-2021.csv', '04-18-2021.csv', '02-08-2020.csv', '10-10-2021.csv', '02-09-2020.csv', '10-11-2021.csv', '06-16-2021.csv', '06-17-2021.csv', '03-01-2022.csv', '05-25-2021.csv', '05-24-2021.csv', '06-22-2021.csv', '06-23-2021.csv', '11-18-2021.csv', '11-19-2021.csv', '03-01-2020.csv', '05-11-2021.csv', '05-10-2021.csv', '02-08-2022.csv', '02-09-2022.csv', '09-07-2021.csv', '09-06-2021.csv', '10-24-2021.csv', '10-25-2021.csv', '04-12-2020.csv', '07-15-2022.csv', '04-13-2020.csv', '07-14-2022.csv', '01-30-2021.csv', '01-31-2021.csv', '04-26-2022.csv', '07-21-2020.csv', '04-27-2022.csv', '07-20-2020.csv', '01-04-2023.csv', '02-03-2021.csv', '01-05-2023.csv', '02-02-2021.csv', '08-04-2020.csv', '08-05-2020.csv', '11-27-2020.csv', '12-20-2022.csv', '11-26-2020.csv', '12-21-2022.csv', '08-30-2022.csv', '06-29-2022.csv', '06-28-2022.csv', '08-31-2022.csv', '11-13-2022.csv', '12-14-2020.csv', '11-12-2022.csv', '12-15-2020.csv', '12-15-2021.csv', '12-14-2021.csv', '11-26-2021.csv', '11-27-2021.csv', '08-05-2021.csv', '08-04-2021.csv', '02-02-2020.csv', '01-05-2022.csv', '02-03-2020.csv', '01-04-2022.csv', '07-20-2021.csv', '07-21-2021.csv', '01-31-2020.csv', '01-30-2020.csv', '04-13-2021.csv', '04-12-2021.csv', '10-25-2020.csv', '10-24-2020.csv', '04-18-2022.csv', '09-06-2020.csv', '09-07-2020.csv', '04-19-2022.csv', '10-11-2022.csv', '02-09-2023.csv', '10-10-2022.csv', '02-08-2023.csv', '05-10-2020.csv', '06-17-2022.csv', '05-11-2020.csv', '06-16-2022.csv', '11-19-2020.csv', '03-01-2021.csv', '11-18-2020.csv', '05-24-2022.csv', '06-23-2020.csv', '05-25-2022.csv', '06-22-2020.csv', '03-29-2022.csv', '03-28-2022.csv', '11-05-2021.csv', '11-04-2021.csv', '08-26-2021.csv', '08-27-2021.csv', '02-21-2020.csv', '01-26-2022.csv', '02-20-2020.csv', '01-27-2022.csv', '07-03-2021.csv', '07-02-2021.csv', '02-15-2022.csv', '02-14-2022.csv', '04-30-2021.csv', '01-19-2023.csv', '10-06-2020.csv', '01-18-2023.csv', '10-07-2020.csv', '09-25-2020.csv', '09-24-2020.csv', '09-11-2022.csv', '07-08-2022.csv', '07-09-2022.csv', '09-10-2022.csv', '12-09-2020.csv', '12-08-2020.csv', '03-22-2021.csv', '03-23-2021.csv', '05-07-2022.csv', '08-19-2020.csv', '08-18-2020.csv', '05-06-2022.csv', '06-01-2020.csv', '06-01-2021.csv', '08-18-2021.csv', '08-19-2021.csv', '03-23-2020.csv', '03-22-2020.csv', '03-17-2022.csv', '12-08-2021.csv', '03-16-2022.csv', '12-09-2021.csv', '09-24-2021.csv', '09-25-2021.csv', '01-18-2022.csv', '10-07-2021.csv', '01-19-2022.csv', '10-06-2021.csv', '04-30-2020.csv', '01-13-2021.csv', '02-14-2023.csv', '01-12-2021.csv', '02-15-2023.csv', '04-05-2022.csv', '07-02-2020.csv', '04-04-2022.csv', '07-03-2020.csv', '01-27-2023.csv', '02-20-2021.csv', '01-26-2023.csv', '02-21-2021.csv', '08-27-2020.csv', '08-26-2020.csv', '11-04-2020.csv', '12-03-2022.csv', '11-05-2020.csv', '12-02-2022.csv', '08-13-2022.csv', '08-12-2022.csv', '11-30-2022.csv', '11-30-2020.csv', '03-28-2021.csv', '03-29-2021.csv', '08-13-2020.csv', '08-12-2020.csv', '12-03-2020.csv', '11-04-2022.csv', '12-02-2020.csv', '11-05-2022.csv', '08-27-2022.csv', '08-26-2022.csv', '02-20-2023.csv', '01-27-2021.csv', '02-21-2023.csv', '01-26-2021.csv', '07-02-2022.csv', '04-05-2020.csv', '07-03-2022.csv', '04-04-2020.csv', '02-14-2021.csv', '01-13-2023.csv', '02-15-2021.csv', '01-12-2023.csv', '04-30-2022.csv', '07-09-2021.csv', '09-10-2021.csv', '09-11-2021.csv', '07-08-2021.csv', '03-17-2020.csv', '03-16-2020.csv', '03-23-2022.csv', '03-22-2022.csv', '05-06-2021.csv', '05-07-2021.csv', '08-19-2022.csv', '05-07-2020.csv', '06-01-2022.csv', '05-06-2020.csv', '08-18-2022.csv', '12-09-2022.csv', '03-16-2021.csv', '12-08-2022.csv', '03-17-2021.csv', '07-08-2020.csv', '09-11-2020.csv', '09-10-2020.csv', '07-09-2020.csv', '09-25-2022.csv', '09-24-2022.csv', '10-06-2022.csv', '01-19-2021.csv', '10-07-2022.csv', '01-18-2021.csv', '01-12-2022.csv', '02-15-2020.csv', '01-13-2022.csv', '02-14-2020.csv', '04-04-2021.csv', '04-05-2021.csv', '01-26-2020.csv', '02-21-2022.csv', '01-27-2020.csv', '02-20-2022.csv', '12-02-2021.csv', '12-03-2021.csv', '08-12-2021.csv', '08-13-2021.csv', '03-29-2020.csv', '11-30-2021.csv', '03-28-2020.csv', '09-03-2021.csv', '09-02-2021.csv', '10-20-2021.csv', '10-21-2021.csv', '04-29-2021.csv', '04-28-2021.csv', '05-15-2021.csv', '05-14-2021.csv', '03-30-2022.csv', '03-31-2022.csv', '06-26-2021.csv', '06-27-2021.csv', '03-04-2020.csv', '03-05-2020.csv', '12-10-2020.csv', '11-17-2022.csv', '12-11-2020.csv', '11-16-2022.csv', '06-19-2020.csv', '06-18-2020.csv', '08-01-2020.csv', '12-24-2022.csv', '11-23-2020.csv', '12-25-2022.csv', '11-22-2020.csv', '07-25-2020.csv', '04-22-2022.csv', '07-24-2020.csv', '04-23-2022.csv', '02-07-2021.csv', '02-06-2021.csv', '01-01-2023.csv', '07-11-2022.csv', '04-16-2020.csv', '09-08-2022.csv', '09-09-2022.csv', '07-10-2022.csv', '04-17-2020.csv', '04-17-2021.csv', '04-16-2021.csv', '01-01-2022.csv', '02-06-2020.csv', '02-07-2020.csv', '07-24-2021.csv', '07-25-2021.csv', '11-22-2021.csv', '11-23-2021.csv', '08-01-2021.csv', '06-18-2021.csv', '06-19-2021.csv', '12-11-2021.csv', '12-10-2021.csv', '03-05-2021.csv', '03-04-2021.csv', '06-27-2020.csv', '05-20-2022.csv', '06-26-2020.csv', '05-21-2022.csv', '11-29-2022.csv', '11-28-2022.csv', '06-13-2022.csv', '05-14-2020.csv', '06-12-2022.csv', '05-15-2020.csv', '10-15-2022.csv', '10-14-2022.csv', '04-28-2020.csv', '04-29-2020.csv', '10-21-2020.csv', '10-20-2020.csv', '09-02-2020.csv', '09-03-2020.csv', '09-02-2022.csv', '09-03-2022.csv', '10-21-2022.csv', '10-20-2022.csv', '04-28-2022.csv', '04-29-2022.csv', '10-15-2020.csv', '10-14-2020.csv', '05-14-2022.csv', '06-13-2020.csv', '05-15-2022.csv', '06-12-2020.csv', '03-31-2021.csv', '11-29-2020.csv', '03-30-2021.csv', '11-28-2020.csv', '05-20-2020.csv', '06-27-2022.csv', '05-21-2020.csv', '06-26-2022.csv', '03-05-2023.csv', '03-04-2023.csv', '11-16-2021.csv', '11-17-2021.csv', '12-25-2021.csv', '12-24-2021.csv', '04-23-2021.csv', '04-22-2021.csv', '02-06-2022.csv', '02-07-2022.csv', '09-09-2021.csv', '07-10-2021.csv', '07-11-2021.csv', '09-08-2021.csv', '09-08-2020.csv', '04-16-2022.csv', '07-11-2020.csv', '04-17-2022.csv', '07-10-2020.csv', '09-09-2020.csv', '02-07-2023.csv', '01-01-2021.csv', '02-06-2023.csv', '04-22-2020.csv', '07-25-2022.csv', '04-23-2020.csv', '07-24-2022.csv', '11-23-2022.csv', '12-24-2020.csv', '11-22-2022.csv', '12-25-2020.csv', '06-19-2022.csv', '08-01-2022.csv', '06-18-2022.csv', '11-17-2020.csv', '12-10-2022.csv', '11-16-2020.csv', '12-11-2022.csv', '03-04-2022.csv', '03-05-2022.csv', '05-21-2021.csv', '05-20-2021.csv', '03-30-2020.csv', '11-28-2021.csv', '03-31-2020.csv', '11-29-2021.csv', '06-12-2021.csv', '06-13-2021.csv', '10-14-2021.csv', '10-15-2021.csv', '10-08-2020.csv', '01-17-2023.csv', '02-10-2021.csv', '10-09-2020.csv', '01-16-2023.csv', '02-11-2021.csv', '01-23-2021.csv', '02-24-2023.csv', '01-22-2021.csv', '02-25-2023.csv', '04-01-2020.csv', '07-06-2022.csv', '07-07-2022.csv', '12-07-2020.csv', '11-01-2022.csv', '12-06-2020.csv', '08-23-2022.csv', '08-22-2022.csv', '08-17-2020.csv', '05-09-2022.csv', '05-08-2022.csv', '08-16-2020.csv', '03-27-2022.csv', '03-26-2022.csv', '05-02-2021.csv', '05-03-2021.csv', '03-13-2020.csv', '03-12-2020.csv', '08-28-2021.csv', '06-30-2021.csv', '08-29-2021.csv', '01-28-2022.csv', '01-29-2022.csv', '09-14-2021.csv', '09-15-2021.csv', '09-21-2022.csv', '09-20-2022.csv', '10-02-2022.csv', '10-03-2022.csv', '09-15-2020.csv', '09-14-2020.csv', '01-29-2023.csv', '01-28-2023.csv', '08-29-2020.csv', '06-30-2020.csv', '08-28-2020.csv', '03-12-2021.csv', '03-13-2021.csv', '05-03-2020.csv', '06-04-2022.csv', '05-02-2020.csv', '06-05-2022.csv', '08-16-2021.csv', '08-17-2021.csv', '12-06-2021.csv', '03-19-2022.csv', '12-07-2021.csv', '03-18-2022.csv', '04-01-2021.csv', '02-25-2022.csv', '01-22-2020.csv', '02-24-2022.csv', '01-23-2020.csv', '10-09-2021.csv', '02-11-2020.csv', '01-16-2022.csv', '10-08-2021.csv', '02-10-2020.csv', '01-17-2022.csv', '02-11-2022.csv', '02-10-2022.csv', '01-22-2022.csv', '02-25-2020.csv', '01-23-2022.csv', '02-24-2020.csv', '07-07-2021.csv', '07-06-2021.csv', '03-19-2020.csv', '11-01-2021.csv', '03-18-2020.csv', '08-22-2021.csv', '08-23-2021.csv', '05-08-2021.csv', '05-09-2021.csv', '03-26-2021.csv', '03-27-2021.csv', '06-04-2020.csv', '05-03-2022.csv', '06-05-2020.csv', '05-02-2022.csv', '06-30-2022.csv', '08-29-2022.csv', '08-28-2022.csv', '01-29-2021.csv', '01-28-2021.csv', '09-15-2022.csv', '09-14-2022.csv', '10-02-2020.csv', '10-03-2020.csv', '09-21-2020.csv', '09-20-2020.csv', '09-20-2021.csv', '09-21-2021.csv', '10-03-2021.csv', '10-02-2021.csv', '01-28-2020.csv', '01-29-2020.csv', '03-13-2022.csv', '03-12-2022.csv', '06-05-2021.csv', '06-04-2021.csv', '03-27-2020.csv', '03-26-2020.csv', '05-09-2020.csv', '08-17-2022.csv', '08-16-2022.csv', '05-08-2020.csv', '08-23-2020.csv', '08-22-2020.csv', '03-18-2021.csv', '12-07-2022.csv', '03-19-2021.csv', '12-06-2022.csv', '11-01-2020.csv', '07-06-2020.csv', '04-01-2022.csv', '07-07-2020.csv', '02-24-2021.csv', '01-23-2023.csv', '02-25-2021.csv', '01-22-2023.csv', '02-10-2023.csv', '01-17-2021.csv', '10-08-2022.csv', '02-11-2023.csv', '01-16-2021.csv', '10-09-2022.csv', '11-07-2022.csv', '12-01-2020.csv', '11-06-2022.csv', '08-24-2022.csv', '08-25-2022.csv', '06-09-2020.csv', '08-10-2020.csv', '08-11-2020.csv', '06-08-2020.csv', '02-17-2021.csv', '01-10-2023.csv', '02-16-2021.csv', '01-11-2023.csv', '02-23-2023.csv', '01-24-2021.csv', '02-22-2023.csv', '01-25-2021.csv', '09-18-2022.csv', '07-01-2022.csv', '04-06-2020.csv', '04-07-2020.csv', '09-19-2022.csv', '10-30-2021.csv', '02-28-2020.csv', '10-31-2021.csv', '02-29-2020.csv', '09-13-2021.csv', '09-12-2021.csv', '03-20-2022.csv', '03-21-2022.csv', '05-05-2021.csv', '05-04-2021.csv', '03-14-2020.csv', '03-15-2020.csv', '05-30-2022.csv', '05-31-2022.csv', '03-15-2021.csv', '03-14-2021.csv', '06-03-2022.csv', '05-04-2020.csv', '06-02-2022.csv', '05-05-2020.csv', '09-26-2022.csv', '09-27-2022.csv', '10-05-2022.csv', '10-04-2022.csv', '09-12-2020.csv', '09-13-2020.csv', '10-31-2020.csv', '10-30-2020.csv', '02-28-2021.csv', '04-07-2021.csv', '04-06-2021.csv', '01-25-2020.csv', '02-22-2022.csv', '01-24-2020.csv', '02-23-2022.csv', '01-11-2022.csv', '02-16-2020.csv', '01-10-2022.csv', '02-17-2020.csv', '06-08-2021.csv', '08-11-2021.csv', '08-10-2021.csv', '06-09-2021.csv', '12-01-2021.csv', '11-06-2021.csv', '11-07-2021.csv', '08-25-2021.csv', '08-24-2021.csv', '02-16-2022.csv', '02-17-2022.csv', '02-22-2020.csv', '01-25-2022.csv', '02-23-2020.csv', '01-24-2022.csv', '09-19-2021.csv', '09-18-2021.csv', '07-01-2021.csv', '10-31-2022.csv', '02-28-2023.csv', '10-30-2022.csv', '09-12-2022.csv', '09-13-2022.csv', '10-05-2020.csv', '10-04-2020.csv', '09-26-2020.csv', '09-27-2020.csv', '03-21-2021.csv', '03-20-2021.csv', '05-04-2022.csv', '06-03-2020.csv', '05-05-2022.csv', '06-02-2020.csv', '05-30-2020.csv', '05-31-2020.csv', '05-31-2021.csv', '05-30-2021.csv', '03-14-2022.csv', '03-15-2022.csv', '06-02-2021.csv', '06-03-2021.csv', '03-20-2020.csv', '03-21-2020.csv', '09-27-2021.csv', '09-26-2021.csv', '10-04-2021.csv', '10-05-2021.csv', '02-28-2022.csv', '04-06-2022.csv', '07-01-2020.csv', '09-18-2020.csv', '09-19-2020.csv', '04-07-2022.csv', '01-24-2023.csv', '02-23-2021.csv', '01-25-2023.csv', '02-22-2021.csv', '01-10-2021.csv', '02-17-2023.csv', '01-11-2021.csv', '02-16-2023.csv', '08-10-2022.csv', '06-09-2022.csv', '06-08-2022.csv', '08-11-2022.csv', '08-24-2020.csv', '08-25-2020.csv', '11-07-2020.csv', '11-06-2020.csv', '12-01-2022.csv', '05-12-2021.csv', '05-13-2021.csv', '12-28-2021.csv', '12-29-2021.csv', '06-21-2021.csv', '06-20-2021.csv', '03-03-2020.csv', '03-02-2020.csv', '09-04-2021.csv', '09-05-2021.csv', '10-27-2021.csv', '10-26-2021.csv', '04-25-2022.csv', '07-22-2020.csv', '04-24-2022.csv', '07-23-2020.csv', '10-18-2020.csv', '01-07-2023.csv', '10-19-2020.csv', '01-06-2023.csv', '02-01-2021.csv', '04-11-2020.csv', '07-16-2022.csv', '04-10-2020.csv', '07-17-2022.csv', '11-10-2022.csv', '12-17-2020.csv', '03-08-2023.csv', '11-11-2022.csv', '12-16-2020.csv', '03-09-2023.csv', '05-19-2022.csv', '08-07-2020.csv', '08-06-2020.csv', '05-18-2022.csv', '11-24-2020.csv', '12-23-2022.csv', '11-25-2020.csv', '12-22-2022.csv', '11-25-2021.csv', '11-24-2021.csv', '08-06-2021.csv', '08-07-2021.csv', '12-16-2021.csv', '03-09-2022.csv', '12-17-2021.csv', '03-08-2022.csv', '04-10-2021.csv', '04-11-2021.csv', '10-19-2021.csv', '02-01-2020.csv', '01-06-2022.csv', '10-18-2021.csv', '01-07-2022.csv', '07-23-2021.csv', '07-22-2021.csv', '10-12-2022.csv', '10-13-2022.csv', '07-28-2022.csv', '07-29-2022.csv', '09-30-2022.csv', '10-26-2020.csv', '10-27-2020.csv', '09-05-2020.csv', '09-04-2020.csv', '03-02-2021.csv', '03-03-2021.csv', '05-27-2022.csv', '06-20-2020.csv', '05-26-2022.csv', '06-21-2020.csv', '12-29-2020.csv', '12-28-2020.csv', '05-13-2020.csv', '06-14-2022.csv', '05-12-2020.csv', '06-15-2022.csv', '06-14-2020.csv', '05-13-2022.csv', '06-15-2020.csv', '05-12-2022.csv', '12-29-2022.csv', '12-28-2022.csv', '06-20-2022.csv', '05-27-2020.csv', '06-21-2022.csv', '05-26-2020.csv', '03-02-2023.csv', '03-03-2023.csv', '09-05-2022.csv', '09-04-2022.csv', '10-26-2022.csv', '10-27-2022.csv', '07-28-2020.csv', '09-30-2020.csv', '07-29-2020.csv', '10-12-2020.csv', '10-13-2020.csv', '04-24-2021.csv', '04-25-2021.csv', '02-01-2022.csv', '07-17-2021.csv', '07-16-2021.csv', '03-09-2020.csv', '11-11-2021.csv', '03-08-2020.csv', '11-10-2021.csv', '05-18-2021.csv', '05-19-2021.csv', '12-22-2021.csv', '12-23-2021.csv', '12-23-2020.csv', '11-24-2022.csv', '12-22-2020.csv', '11-25-2022.csv', '08-07-2022.csv', '05-19-2020.csv', '

In [78]:
from datetime import datetime

csv_list.sort(key=lambda x : datetime.strptime(x, "%m-%d-%Y.csv"))
csv_list

['01-22-2020.csv',
 '01-23-2020.csv',
 '01-24-2020.csv',
 '01-25-2020.csv',
 '01-26-2020.csv',
 '01-27-2020.csv',
 '01-28-2020.csv',
 '01-29-2020.csv',
 '01-30-2020.csv',
 '01-31-2020.csv',
 '02-01-2020.csv',
 '02-02-2020.csv',
 '02-03-2020.csv',
 '02-04-2020.csv',
 '02-05-2020.csv',
 '02-06-2020.csv',
 '02-07-2020.csv',
 '02-08-2020.csv',
 '02-09-2020.csv',
 '02-10-2020.csv',
 '02-11-2020.csv',
 '02-12-2020.csv',
 '02-13-2020.csv',
 '02-14-2020.csv',
 '02-15-2020.csv',
 '02-16-2020.csv',
 '02-17-2020.csv',
 '02-18-2020.csv',
 '02-19-2020.csv',
 '02-20-2020.csv',
 '02-21-2020.csv',
 '02-22-2020.csv',
 '02-23-2020.csv',
 '02-24-2020.csv',
 '02-25-2020.csv',
 '02-26-2020.csv',
 '02-27-2020.csv',
 '02-28-2020.csv',
 '02-29-2020.csv',
 '03-01-2020.csv',
 '03-02-2020.csv',
 '03-03-2020.csv',
 '03-04-2020.csv',
 '03-05-2020.csv',
 '03-06-2020.csv',
 '03-07-2020.csv',
 '03-08-2020.csv',
 '03-09-2020.csv',
 '03-10-2020.csv',
 '03-11-2020.csv',
 '03-12-2020.csv',
 '03-13-2020.csv',
 '03-14-2020.csv',
 '03-15-2020.csv',
 '03-16-2020.csv',
 '03-17-2020.csv',
 '03-18-2020.csv',
 '03-19-2020.csv',
 '03-20-2020.csv',
 '03-21-2020.csv',
 '03-22-2020.csv',
 '03-23-2020.csv',
 '03-24-2020.csv',
 '03-25-2020.csv',
 '03-26-2020.csv',
 '03-27-2020.csv',
 '03-28-2020.csv',
 '03-29-2020.csv',
 '03-30-2020.csv',
 '03-31-2020.csv',
 '04-01-2020.csv',
 '04-02-2020.csv',
 '04-03-2020.csv',
 '04-04-2020.csv',
 '04-05-2020.csv',
 '04-06-2020.csv',
 '04-07-2020.csv',
 '04-08-2020.csv',
 '04-09-2020.csv',
 '04-10-2020.csv',
 '04-11-2020.csv',
 '04-12-2020.csv',
 '04-13-2020.csv',
 '04-14-2020.csv',
 '04-15-2020.csv',
 '04-16-2020.csv',
 '04-17-2020.csv',
 '04-18-2020.csv',
 '04-19-2020.csv',
 '04-20-2020.csv',
 '04-21-2020.csv',
 '04-22-2020.csv',
 '04-23-2020.csv',
 '04-24-2020.csv',
 '04-25-2020.csv',
 '04-26-2020.csv',
 '04-27-2020.csv',
 '04-28-2020.csv',
 '04-29-2020.csv',
 '04-30-2020.csv',
 '05-01-2020.csv',
 '05-02-2020.csv',
 '05-03-2020.csv',
 '05-04-2020.csv',
 '05-05-2020.csv',
 '05-06-2020.csv',
 '05-07-2020.csv',
 '05-08-2020.csv',
 '05-09-2020.csv',
 '05-10-2020.csv',
 '05-11-2020.csv',
 '05-12-2020.csv',
 '05-13-2020.csv',
 '05-14-2020.csv',
 '05-15-2020.csv',
 '05-16-2020.csv',
 '05-17-2020.csv',
 '05-18-2020.csv',
 '05-19-2020.csv',
 '05-20-2020.csv',
 '05-21-2020.csv',
 '05-22-2020.csv',
 '05-23-2020.csv',
 '05-24-2020.csv',
 '05-25-2020.csv',
 '05-26-2020.csv',
 '05-27-2020.csv',
 '05-28-2020.csv',
 '05-29-2020.csv',
 '05-30-2020.csv',
 '05-31-2020.csv',
 '06-01-2020.csv',
 '06-02-2020.csv',
 '06-03-2020.csv',
 '06-04-2020.csv',
 '06-05-2020.csv',
 '06-06-2020.csv',
 '06-07-2020.csv',
 '06-08-2020.csv',
 '06-09-2020.csv',
 '06-10-2020.csv',
 '06-11-2020.csv',
 '06-12-2020.csv',
 '06-13-2020.csv',
 '06-14-2020.csv',
 '06-15-2020.csv',
 '06-16-2020.csv',
 '06-17-2020.csv',
 '06-18-2020.csv',
 '06-19-2020.csv',
 '06-20-2020.csv',
 '06-21-2020.csv',
 '06-22-2020.csv',
 '06-23-2020.csv',
 '06-24-2020.csv',
 '06-25-2020.csv',
 '06-26-2020.csv',
 '06-27-2020.csv',
 '06-28-2020.csv',
 '06-29-2020.csv',
 '06-30-2020.csv',
 '07-01-2020.csv',
 '07-02-2020.csv',
 '07-03-2020.csv',
 '07-04-2020.csv',
 '07-05-2020.csv',
 '07-06-2020.csv',
 '07-07-2020.csv',
 '07-08-2020.csv',
 '07-09-2020.csv',
 '07-10-2020.csv',
 '07-11-2020.csv',
 '07-12-2020.csv',
 '07-13-2020.csv',
 '07-14-2020.csv',
 '07-15-2020.csv',
 '07-16-2020.csv',
 '07-17-2020.csv',
 '07-18-2020.csv',
 '07-19-2020.csv',
 '07-20-2020.csv',
 '07-21-2020.csv',
 '07-22-2020.csv',
 '07-23-2020.csv',
 '07-24-2020.csv',
 '07-25-2020.csv',
 '07-26-2020.csv',
 '07-27-2020.csv',
 '07-28-2020.csv',
 '07-29-2020.csv',
 '07-30-2020.csv',
 '07-31-2020.csv',
 '08-01-2020.csv',
 '08-02-2020.csv',
 '08-03-2020.csv',
 '08-04-2020.csv',
 '08-05-2020.csv',
 '08-06-2020.csv',
 '08-07-2020.csv',
 '08-08-2020.csv',
 '08-09-2020.csv',
 '08-10-2020.csv',
 '08-11-2020.csv',
 '08-12-2020.csv',
 '08-13-2020.csv',
 '08-14-2020.csv',
 '08-15-2020.csv',
 '08-16-2020.csv',
 '08-17-2020.csv',
 '08-18-2020.csv',
 '08-19-2020.csv',
 '08-20-2020.csv',
 '08-21-2020.csv',
 '08-22-2020.csv',
 '08-23-2020.csv',
 '08-24-2020.csv',
 '08-25-2020.csv',
 '08-26-2020.csv',
 '08-27-2020.csv',
 '08-28-2020.csv',
 '08-29-2020.csv',
 '08-30-2020.csv',
 '08-31-2020.csv',
 '09-01-2020.csv',
 '09-02-2020.csv',
 '09-03-2020.csv',
 '09-04-2020.csv',
 '09-05-2020.csv',
 '09-06-2020.csv',
 '09-07-2020.csv',
 '09-08-2020.csv',
 '09-09-2020.csv',
 '09-10-2020.csv',
 '09-11-2020.csv',
 '09-12-2020.csv',
 '09-13-2020.csv',
 '09-14-2020.csv',
 '09-15-2020.csv',
 '09-16-2020.csv',
 '09-17-2020.csv',
 '09-18-2020.csv',
 '09-19-2020.csv',
 '09-20-2020.csv',
 '09-21-2020.csv',
 '09-22-2020.csv',
 '09-23-2020.csv',
 '09-24-2020.csv',
 '09-25-2020.csv',
 '09-26-2020.csv',
 '09-27-2020.csv',
 '09-28-2020.csv',
 '09-29-2020.csv',
 '09-30-2020.csv',
 '10-01-2020.csv',
 '10-02-2020.csv',
 '10-03-2020.csv',
 '10-04-2020.csv',
 '10-05-2020.csv',
 '10-06-2020.csv',
 '10-07-2020.csv',
 '10-08-2020.csv',
 '10-09-2020.csv',
 '10-10-2020.csv',
 '10-11-2020.csv',
 '10-12-2020.csv',
 '10-13-2020.csv',
 '10-14-2020.csv',
 '10-15-2020.csv',
 '10-16-2020.csv',
 '10-17-2020.csv',
 '10-18-2020.csv',
 '10-19-2020.csv',
 '10-20-2020.csv',
 '10-21-2020.csv',
 '10-22-2020.csv',
 '10-23-2020.csv',
 '10-24-2020.csv',
 '10-25-2020.csv',
 '10-26-2020.csv',
 '10-27-2020.csv',
 '10-28-2020.csv',
 '10-29-2020.csv',
 '10-30-2020.csv',
 '10-31-2020.csv',
 '11-01-2020.csv',
 '11-02-2020.csv',
 '11-03-2020.csv',
 '11-04-2020.csv',
 '11-05-2020.csv',
 '11-06-2020.csv',
 '11-07-2020.csv',
 '11-08-2020.csv',
 '11-09-2020.csv',
 '11-10-2020.csv',
 '11-11-2020.csv',
 '11-12-2020.csv',
 '11-13-2020.csv',
 '11-14-2020.csv',
 '11-15-2020.csv',
 '11-16-2020.csv',
 '11-17-2020.csv',
 '11-18-2020.csv',
 '11-19-2020.csv',
 '11-20-2020.csv',
 '11-21-2020.csv',
 '11-22-2020.csv',
 '11-23-2020.csv',
 '11-24-2020.csv',
 '11-25-2020.csv',
 '11-26-2020.csv',
 '11-27-2020.csv',
 '11-28-2020.csv',
 '11-29-2020.csv',
 '11-30-2020.csv',
 '12-01-2020.csv',
 '12-02-2020.csv',
 '12-03-2020.csv',
 '12-04-2020.csv',
 '12-05-2020.csv',
 '12-06-2020.csv',
 '12-07-2020.csv',
 '12-08-2020.csv',
 '12-09-2020.csv',
 '12-10-2020.csv',
 '12-11-2020.csv',
 '12-12-2020.csv',
 '12-13-2020.csv',
 '12-14-2020.csv',
 '12-15-2020.csv',
 '12-16-2020.csv',
 '12-17-2020.csv',
 '12-18-2020.csv',
 '12-19-2020.csv',
 '12-20-2020.csv',
 '12-21-2020.csv',
 '12-22-2020.csv',
 '12-23-2020.csv',
 '12-24-2020.csv',
 '12-25-2020.csv',
 '12-26-2020.csv',
 '12-27-2020.csv',
 '12-28-2020.csv',
 '12-29-2020.csv',
 '12-30-2020.csv',
 '12-31-2020.csv',
 '01-01-2021.csv',
 '01-02-2021.csv',
 '01-03-2021.csv',
 '01-04-2021.csv',
 '01-05-2021.csv',
 '01-06-2021.csv',
 '01-07-2021.csv',
 '01-08-2021.csv',
 '01-09-2021.csv',
 '01-10-2021.csv',
 '01-11-2021.csv',
 '01-12-2021.csv',
 '01-13-2021.csv',
 '01-14-2021.csv',
 '01-15-2021.csv',
 '01-16-2021.csv',
 '01-17-2021.csv',
 '01-18-2021.csv',
 '01-19-2021.csv',
 '01-20-2021.csv',
 '01-21-2021.csv',
 '01-22-2021.csv',
 '01-23-2021.csv',
 '01-24-2021.csv',
 '01-25-2021.csv',
 '01-26-2021.csv',
 '01-27-2021.csv',
 '01-28-2021.csv',
 '01-29-2021.csv',
 '01-30-2021.csv',
 '01-31-2021.csv',
 '02-01-2021.csv',
 '02-02-2021.csv',
 '02-03-2021.csv',
 '02-04-2021.csv',
 '02-05-2021.csv',
 '02-06-2021.csv',
 '02-07-2021.csv',
 '02-08-2021.csv',
 '02-09-2021.csv',
 '02-10-2021.csv',
 '02-11-2021.csv',
 '02-12-2021.csv',
 '02-13-2021.csv',
 '02-14-2021.csv',
 '02-15-2021.csv',
 '02-16-2021.csv',
 '02-17-2021.csv',
 '02-18-2021.csv',
 '02-19-2021.csv',
 '02-20-2021.csv',
 '02-21-2021.csv',
 '02-22-2021.csv',
 '02-23-2021.csv',
 '02-24-2021.csv',
 '02-25-2021.csv',
 '02-26-2021.csv',
 '02-27-2021.csv',
 '02-28-2021.csv',
 '03-01-2021.csv',
 '03-02-2021.csv',
 '03-03-2021.csv',
 '03-04-2021.csv',
 '03-05-2021.csv',
 '03-06-2021.csv',
 '03-07-2021.csv',
 '03-08-2021.csv',
 '03-09-2021.csv',
 '03-10-2021.csv',
 '03-11-2021.csv',
 '03-12-2021.csv',
 '03-13-2021.csv',
 '03-14-2021.csv',
 '03-15-2021.csv',
 '03-16-2021.csv',
 '03-17-2021.csv',
 '03-18-2021.csv',
 '03-19-2021.csv',
 '03-20-2021.csv',
 '03-21-2021.csv',
 '03-22-2021.csv',
 '03-23-2021.csv',
 '03-24-2021.csv',
 '03-25-2021.csv',
 '03-26-2021.csv',
 '03-27-2021.csv',
 '03-28-2021.csv',
 '03-29-2021.csv',
 '03-30-2021.csv',
 '03-31-2021.csv',
 '04-01-2021.csv',
 '04-02-2021.csv',
 '04-03-2021.csv',
 '04-04-2021.csv',
 '04-05-2021.csv',
 '04-06-2021.csv',
 '04-07-2021.csv',
 '04-08-2021.csv',
 '04-09-2021.csv',
 '04-10-2021.csv',
 '04-11-2021.csv',
 '04-12-2021.csv',
 '04-13-2021.csv',
 '04-14-2021.csv',
 '04-15-2021.csv',
 '04-16-2021.csv',
 '04-17-2021.csv',
 '04-18-2021.csv',
 '04-19-2021.csv',
 '04-20-2021.csv',
 '04-21-2021.csv',
 '04-22-2021.csv',
 '04-23-2021.csv',
 '04-24-2021.csv',
 '04-25-2021.csv',
 '04-26-2021.csv',
 '04-27-2021.csv',
 '04-28-2021.csv',
 '04-29-2021.csv',
 '04-30-2021.csv',
 '05-01-2021.csv',
 '05-02-2021.csv',
 '05-03-2021.csv',
 '05-04-2021.csv',
 '05-05-2021.csv',
 '05-06-2021.csv',
 '05-07-2021.csv',
 '05-08-2021.csv',
 '05-09-2021.csv',
 '05-10-2021.csv',
 '05-11-2021.csv',
 '05-12-2021.csv',
 '05-13-2021.csv',
 '05-14-2021.csv',
 '05-15-2021.csv',
 '05-16-2021.csv',
 '05-17-2021.csv',
 '05-18-2021.csv',
 '05-19-2021.csv',
 '05-20-2021.csv',
 '05-21-2021.csv',
 '05-22-2021.csv',
 '05-23-2021.csv',
 '05-24-2021.csv',
 '05-25-2021.csv',
 '05-26-2021.csv',
 '05-27-2021.csv',
 '05-28-2021.csv',
 '05-29-2021.csv',
 '05-30-2021.csv',
 '05-31-2021.csv',
 '06-01-2021.csv',
 '06-02-2021.csv',
 '06-03-2021.csv',
 '06-04-2021.csv',
 '06-05-2021.csv',
 '06-06-2021.csv',
 '06-07-2021.csv',
 '06-08-2021.csv',
 '06-09-2021.csv',
 '06-10-2021.csv',
 '06-11-2021.csv',
 '06-12-2021.csv',
 '06-13-2021.csv',
 '06-14-2021.csv',
 '06-15-2021.csv',
 '06-16-2021.csv',
 '06-17-2021.csv',
 '06-18-2021.csv',
 '06-19-2021.csv',
 '06-20-2021.csv',
 '06-21-2021.csv',
 '06-22-2021.csv',
 '06-23-2021.csv',
 '06-24-2021.csv',
 '06-25-2021.csv',
 '06-26-2021.csv',
 '06-27-2021.csv',
 '06-28-2021.csv',
 '06-29-2021.csv',
 '06-30-2021.csv',
 '07-01-2021.csv',
 '07-02-2021.csv',
 '07-03-2021.csv',
 '07-04-2021.csv',
 '07-05-2021.csv',
 '07-06-2021.csv',
 '07-07-2021.csv',
 '07-08-2021.csv',
 '07-09-2021.csv',
 '07-10-2021.csv',
 '07-11-2021.csv',
 '07-12-2021.csv',
 '07-13-2021.csv',
 '07-14-2021.csv',
 '07-15-2021.csv',
 '07-16-2021.csv',
 '07-17-2021.csv',
 '07-18-2021.csv',
 '07-19-2021.csv',
 '07-20-2021.csv',
 '07-21-2021.csv',
 '07-22-2021.csv',
 '07-23-2021.csv',
 '07-24-2021.csv',
 '07-25-2021.csv',
 '07-26-2021.csv',
 '07-27-2021.csv',
 '07-28-2021.csv',
 '07-29-2021.csv',
 '07-30-2021.csv',
 '07-31-2021.csv',
 '08-01-2021.csv',
 '08-02-2021.csv',
 '08-03-2021.csv',
 '08-04-2021.csv',
 '08-05-2021.csv',
 '08-06-2021.csv',
 '08-07-2021.csv',
 '08-08-2021.csv',
 '08-09-2021.csv',
 '08-10-2021.csv',
 '08-11-2021.csv',
 '08-12-2021.csv',
 '08-13-2021.csv',
 '08-14-2021.csv',
 '08-15-2021.csv',
 '08-16-2021.csv',
 '08-17-2021.csv',
 '08-18-2021.csv',
 '08-19-2021.csv',
 '08-20-2021.csv',
 '08-21-2021.csv',
 '08-22-2021.csv',
 '08-23-2021.csv',
 '08-24-2021.csv',
 '08-25-2021.csv',
 '08-26-2021.csv',
 '08-27-2021.csv',
 '08-28-2021.csv',
 '08-29-2021.csv',
 '08-30-2021.csv',
 '08-31-2021.csv',
 '09-01-2021.csv',
 '09-02-2021.csv',
 '09-03-2021.csv',
 '09-04-2021.csv',
 '09-05-2021.csv',
 '09-06-2021.csv',
 '09-07-2021.csv',
 '09-08-2021.csv',
 '09-09-2021.csv',
 '09-10-2021.csv',
 '09-11-2021.csv',
 '09-12-2021.csv',
 '09-13-2021.csv',
 '09-14-2021.csv',
 '09-15-2021.csv',
 '09-16-2021.csv',
 '09-17-2021.csv',
 '09-18-2021.csv',
 '09-19-2021.csv',
 '09-20-2021.csv',
 '09-21-2021.csv',
 '09-22-2021.csv',
 '09-23-2021.csv',
 '09-24-2021.csv',
 '09-25-2021.csv',
 '09-26-2021.csv',
 '09-27-2021.csv',
 '09-28-2021.csv',
 '09-29-2021.csv',
 '09-30-2021.csv',
 '10-01-2021.csv',
 '10-02-2021.csv',
 '10-03-2021.csv',
 '10-04-2021.csv',
 '10-05-2021.csv',
 '10-06-2021.csv',
 '10-07-2021.csv',
 '10-08-2021.csv',
 '10-09-2021.csv',
 '10-10-2021.csv',
 '10-11-2021.csv',
 '10-12-2021.csv',
 '10-13-2021.csv',
 '10-14-2021.csv',
 '10-15-2021.csv',
 '10-16-2021.csv',
 '10-17-2021.csv',
 '10-18-2021.csv',
 '10-19-2021.csv',
 '10-20-2021.csv',
 '10-21-2021.csv',
 '10-22-2021.csv',
 '10-23-2021.csv',
 '10-24-2021.csv',
 '10-25-2021.csv',
 '10-26-2021.csv',
 '10-27-2021.csv',
 '10-28-2021.csv',
 '10-29-2021.csv',
 '10-30-2021.csv',
 '10-31-2021.csv',
 '11-01-2021.csv',
 '11-02-2021.csv',
 '11-03-2021.csv',
 '11-04-2021.csv',
 '11-05-2021.csv',
 '11-06-2021.csv',
 '11-07-2021.csv',
 '11-08-2021.csv',
 '11-09-2021.csv',
 '11-10-2021.csv',
 '11-11-2021.csv',
 '11-12-2021.csv',
 '11-13-2021.csv',
 '11-14-2021.csv',
 '11-15-2021.csv',
 '11-16-2021.csv',
 '11-17-2021.csv',
 '11-18-2021.csv',
 '11-19-2021.csv',
 '11-20-2021.csv',
 '11-21-2021.csv',
 '11-22-2021.csv',
 '11-23-2021.csv',
 '11-24-2021.csv',
 '11-25-2021.csv',
 '11-26-2021.csv',
 '11-27-2021.csv',
 '11-28-2021.csv',
 '11-29-2021.csv',
 '11-30-2021.csv',
 '12-01-2021.csv',
 '12-02-2021.csv',
 '12-03-2021.csv',
 '12-04-2021.csv',
 '12-05-2021.csv',
 '12-06-2021.csv',
 '12-07-2021.csv',
 '12-08-2021.csv',
 '12-09-2021.csv',
 '12-10-2021.csv',
 '12-11-2021.csv',
 '12-12-2021.csv',
 '12-13-2021.csv',
 '12-14-2021.csv',
 '12-15-2021.csv',
 '12-16-2021.csv',
 '12-17-2021.csv',
 '12-18-2021.csv',
 '12-19-2021.csv',
 '12-20-2021.csv',
 '12-21-2021.csv',
 '12-22-2021.csv',
 '12-23-2021.csv',
 '12-24-2021.csv',
 '12-25-2021.csv',
 '12-26-2021.csv',
 '12-27-2021.csv',
 '12-28-2021.csv',
 '12-29-2021.csv',
 '12-30-2021.csv',
 '12-31-2021.csv',
 '01-01-2022.csv',
 '01-02-2022.csv',
 '01-03-2022.csv',
 '01-04-2022.csv',
 '01-05-2022.csv',
 '01-06-2022.csv',
 '01-07-2022.csv',
 '01-08-2022.csv',
 '01-09-2022.csv',
 '01-10-2022.csv',
 '01-11-2022.csv',
 '01-12-2022.csv',
 '01-13-2022.csv',
 '01-14-2022.csv',
 '01-15-2022.csv',
 '01-16-2022.csv',
 '01-17-2022.csv',
 '01-18-2022.csv',
 '01-19-2022.csv',
 '01-20-2022.csv',
 '01-21-2022.csv',
 '01-22-2022.csv',
 '01-23-2022.csv',
 '01-24-2022.csv',
 '01-25-2022.csv',
 '01-26-2022.csv',
 '01-27-2022.csv',
 '01-28-2022.csv',
 '01-29-2022.csv',
 '01-30-2022.csv',
 '01-31-2022.csv',
 '02-01-2022.csv',
 '02-02-2022.csv',
 '02-03-2022.csv',
 '02-04-2022.csv',
 '02-05-2022.csv',
 '02-06-2022.csv',
 '02-07-2022.csv',
 '02-08-2022.csv',
 '02-09-2022.csv',
 '02-10-2022.csv',
 '02-11-2022.csv',
 '02-12-2022.csv',
 '02-13-2022.csv',
 '02-14-2022.csv',
 '02-15-2022.csv',
 '02-16-2022.csv',
 '02-17-2022.csv',
 '02-18-2022.csv',
 '02-19-2022.csv',
 '02-20-2022.csv',
 '02-21-2022.csv',
 '02-22-2022.csv',
 '02-23-2022.csv',
 '02-24-2022.csv',
 '02-25-2022.csv',
 '02-26-2022.csv',
 '02-27-2022.csv',
 '02-28-2022.csv',
 '03-01-2022.csv',
 '03-02-2022.csv',
 '03-03-2022.csv',
 '03-04-2022.csv',
 '03-05-2022.csv',
 '03-06-2022.csv',
 '03-07-2022.csv',
 '03-08-2022.csv',
 '03-09-2022.csv',
 '03-10-2022.csv',
 '03-11-2022.csv',
 '03-12-2022.csv',
 '03-13-2022.csv',
 '03-14-2022.csv',
 '03-15-2022.csv',
 '03-16-2022.csv',
 '03-17-2022.csv',
 '03-18-2022.csv',
 '03-19-2022.csv',
 '03-20-2022.csv',
 '03-21-2022.csv',
 '03-22-2022.csv',
 '03-23-2022.csv',
 '03-24-2022.csv',
 '03-25-2022.csv',
 '03-26-2022.csv',
 '03-27-2022.csv',
 '03-28-2022.csv',
 '03-29-2022.csv',
 '03-30-2022.csv',
 '03-31-2022.csv',
 '04-01-2022.csv',
 '04-02-2022.csv',
 '04-03-2022.csv',
 '04-04-2022.csv',
 '04-05-2022.csv',
 '04-06-2022.csv',
 '04-07-2022.csv',
 '04-08-2022.csv',
 '04-09-2022.csv',
 '04-10-2022.csv',
 '04-11-2022.csv',
 '04-12-2022.csv',
 '04-13-2022.csv',
 '04-14-2022.csv',
 '04-15-2022.csv',
 '04-16-2022.csv',
 '04-17-2022.csv',
 '04-18-2022.csv',
 '04-19-2022.csv',
 '04-20-2022.csv',
 '04-21-2022.csv',
 '04-22-2022.csv',
 '04-23-2022.csv',
 '04-24-2022.csv',
 '04-25-2022.csv',
 '04-26-2022.csv',
 '04-27-2022.csv',
 '04-28-2022.csv',
 '04-29-2022.csv',
 '04-30-2022.csv',
 '05-01-2022.csv',
 '05-02-2022.csv',
 '05-03-2022.csv',
 '05-04-2022.csv',
 '05-05-2022.csv',
 '05-06-2022.csv',
 '05-07-2022.csv',
 '05-08-2022.csv',
 '05-09-2022.csv',
 '05-10-2022.csv',
 '05-11-2022.csv',
 '05-12-2022.csv',
 '05-13-2022.csv',
 '05-14-2022.csv',
 '05-15-2022.csv',
 '05-16-2022.csv',
 '05-17-2022.csv',
 '05-18-2022.csv',
 '05-19-2022.csv',
 '05-20-2022.csv',
 '05-21-2022.csv',
 '05-22-2022.csv',
 '05-23-2022.csv',
 '05-24-2022.csv',
 '05-25-2022.csv',
 '05-26-2022.csv',
 '05-27-2022.csv',
 '05-28-2022.csv',
 '05-29-2022.csv',
 '05-30-2022.csv',
 '05-31-2022.csv',
 '06-01-2022.csv',
 '06-02-2022.csv',
 '06-03-2022.csv',
 '06-04-2022.csv',
 '06-05-2022.csv',
 '06-06-2022.csv',
 '06-07-2022.csv',
 '06-08-2022.csv',
 '06-09-2022.csv',
 '06-10-2022.csv',
 '06-11-2022.csv',
 '06-12-2022.csv',
 '06-13-2022.csv',
 '06-14-2022.csv',
 '06-15-2022.csv',
 '06-16-2022.csv',
 '06-17-2022.csv',
 '06-18-2022.csv',
 '06-19-2022.csv',
 '06-20-2022.csv',
 '06-21-2022.csv',
 '06-22-2022.csv',
 '06-23-2022.csv',
 '06-24-2022.csv',
 '06-25-2022.csv',
 '06-26-2022.csv',
 '06-27-2022.csv',
 '06-28-2022.csv',
 '06-29-2022.csv',
 '06-30-2022.csv',
 '07-01-2022.csv',
 '07-02-2022.csv',
 '07-03-2022.csv',
 '07-04-2022.csv',
 '07-05-2022.csv',
 '07-06-2022.csv',
 '07-07-2022.csv',
 '07-08-2022.csv',
 '07-09-2022.csv',
 '07-10-2022.csv',
 '07-11-2022.csv',
 '07-12-2022.csv',
 '07-13-2022.csv',
 '07-14-2022.csv',
 '07-15-2022.csv',
 '07-16-2022.csv',
 '07-17-2022.csv',
 '07-18-2022.csv',
 '07-19-2022.csv',
 '07-20-2022.csv',
 '07-21-2022.csv',
 '07-22-2022.csv',
 '07-23-2022.csv',
 '07-24-2022.csv',
 '07-25-2022.csv',
 '07-26-2022.csv',
 '07-27-2022.csv',
 '07-28-2022.csv',
 '07-29-2022.csv',
 '07-30-2022.csv',
 '07-31-2022.csv',
 '08-01-2022.csv',
 '08-02-2022.csv',
 '08-03-2022.csv',
 '08-04-2022.csv',
 '08-05-2022.csv',
 '08-06-2022.csv',
 '08-07-2022.csv',
 '08-08-2022.csv',
 '08-09-2022.csv',
 '08-10-2022.csv',
 '08-11-2022.csv',
 '08-12-2022.csv',
 '08-13-2022.csv',
 '08-14-2022.csv',
 '08-15-2022.csv',
 '08-16-2022.csv',
 '08-17-2022.csv',
 '08-18-2022.csv',
 '08-19-2022.csv',
 '08-20-2022.csv',
 '08-21-2022.csv',
 '08-22-2022.csv',
 '08-23-2022.csv',
 '08-24-2022.csv',
 '08-25-2022.csv',
 '08-26-2022.csv',
 '08-27-2022.csv',
 '08-28-2022.csv',
 '08-29-2022.csv',
 '08-30-2022.csv',
 '08-31-2022.csv',
 '09-01-2022.csv',
 '09-02-2022.csv',
 '09-03-2022.csv',
 '09-04-2022.csv',
 '09-05-2022.csv',
 '09-06-2022.csv',
 '09-07-2022.csv',
 '09-08-2022.csv',
 '09-09-2022.csv',
 '09-10-2022.csv',
 '09-11-2022.csv',
 '09-12-2022.csv',
 '09-13-2022.csv',
 '09-14-2022.csv',
 '09-15-2022.csv',
 '09-16-2022.csv',
 '09-17-2022.csv',
 '09-18-2022.csv',
 '09-19-2022.csv',
 '09-20-2022.csv',
 '09-21-2022.csv',
 '09-22-2022.csv',
 '09-23-2022.csv',
 '09-24-2022.csv',
 '09-25-2022.csv',
 '09-26-2022.csv',
 '09-27-2022.csv',
 '09-28-2022.csv',
 '09-29-2022.csv',
 '09-30-2022.csv',
 '10-01-2022.csv',
 '10-02-2022.csv',
 '10-03-2022.csv',
 '10-04-2022.csv',
 '10-05-2022.csv',
 '10-06-2022.csv',
 '10-07-2022.csv',
 '10-08-2022.csv',
 '10-09-2022.csv',
 '10-10-2022.csv',
 '10-11-2022.csv',
 '10-12-2022.csv',
 '10-13-2022.csv',
 '10-14-2022.csv',
 '10-15-2022.csv',
 '10-16-2022.csv',
 '10-17-2022.csv',
 ...]

['01-01-2021.csv',
 '01-01-2022.csv',
 '01-01-2023.csv',
 '01-02-2021.csv',
 '01-02-2022.csv',
 '01-02-2023.csv',
 '01-03-2021.csv',
 '01-03-2022.csv',
 '01-03-2023.csv',
 '01-04-2021.csv',
 '01-04-2022.csv',
 '01-04-2023.csv',
 '01-05-2021.csv',
 '01-05-2022.csv',
 '01-05-2023.csv',
 '01-06-2021.csv',
 '01-06-2022.csv',
 '01-06-2023.csv',
 '01-07-2021.csv',
 '01-07-2022.csv',
 '01-07-2023.csv',
 '01-08-2021.csv',
 '01-08-2022.csv',
 '01-08-2023.csv',
 '01-09-2021.csv',
 '01-09-2022.csv',
 '01-09-2023.csv',
 '01-10-2021.csv',
 '01-10-2022.csv',
 '01-10-2023.csv',
 '01-11-2021.csv',
 '01-11-2022.csv',
 '01-11-2023.csv',
 '01-12-2021.csv',
 '01-12-2022.csv',
 '01-12-2023.csv',
 '01-13-2021.csv',
 '01-13-2022.csv',
 '01-13-2023.csv',
 '01-14-2021.csv',
 '01-14-2022.csv',
 '01-14-2023.csv',
 '01-15-2021.csv',
 '01-15-2022.csv',
 '01-15-2023.csv',
 '01-16-2021.csv',
 '01-16-2022.csv',
 '01-16-2023.csv',
 '01-17-2021.csv',
 '01-17-2022.csv',
 '01-17-2023.csv',
 '01-18-2021.csv',
 '01-18-2022.csv',
 '01-18-2023.csv',
 '01-19-2021.csv',
 '01-19-2022.csv',
 '01-19-2023.csv',
 '01-20-2021.csv',
 '01-20-2022.csv',
 '01-20-2023.csv',
 '01-21-2021.csv',
 '01-21-2022.csv',
 '01-21-2023.csv',
 '01-22-2020.csv',
 '01-22-2021.csv',
 '01-22-2022.csv',
 '01-22-2023.csv',
 '01-23-2020.csv',
 '01-23-2021.csv',
 '01-23-2022.csv',
 '01-23-2023.csv',
 '01-24-2020.csv',
 '01-24-2021.csv',
 '01-24-2022.csv',
 '01-24-2023.csv',
 '01-25-2020.csv',
 '01-25-2021.csv',
 '01-25-2022.csv',
 '01-25-2023.csv',
 '01-26-2020.csv',
 '01-26-2021.csv',
 '01-26-2022.csv',
 '01-26-2023.csv',
 '01-27-2020.csv',
 '01-27-2021.csv',
 '01-27-2022.csv',
 '01-27-2023.csv',
 '01-28-2020.csv',
 '01-28-2021.csv',
 '01-28-2022.csv',
 '01-28-2023.csv',
 '01-29-2020.csv',
 '01-29-2021.csv',
 '01-29-2022.csv',
 '01-29-2023.csv',
 '01-30-2020.csv',
 '01-30-2021.csv',
 '01-30-2022.csv',
 '01-30-2023.csv',
 '01-31-2020.csv',
 '01-31-2021.csv',
 '01-31-2022.csv',
 '01-31-2023.csv',
 '02-01-2020.csv',
 '02-01-2021.csv',
 '02-01-2022.csv',
 '02-01-2023.csv',
 '02-02-2020.csv',
 '02-02-2021.csv',
 '02-02-2022.csv',
 '02-02-2023.csv',
 '02-03-2020.csv',
 '02-03-2021.csv',
 '02-03-2022.csv',
 '02-03-2023.csv',
 '02-04-2020.csv',
 '02-04-2021.csv',
 '02-04-2022.csv',
 '02-04-2023.csv',
 '02-05-2020.csv',
 '02-05-2021.csv',
 '02-05-2022.csv',
 '02-05-2023.csv',
 '02-06-2020.csv',
 '02-06-2021.csv',
 '02-06-2022.csv',
 '02-06-2023.csv',
 '02-07-2020.csv',
 '02-07-2021.csv',
 '02-07-2022.csv',
 '02-07-2023.csv',
 '02-08-2020.csv',
 '02-08-2021.csv',
 '02-08-2022.csv',
 '02-08-2023.csv',
 '02-09-2020.csv',
 '02-09-2021.csv',
 '02-09-2022.csv',
 '02-09-2023.csv',
 '02-10-2020.csv',
 '02-10-2021.csv',
 '02-10-2022.csv',
 '02-10-2023.csv',
 '02-11-2020.csv',
 '02-11-2021.csv',
 '02-11-2022.csv',
 '02-11-2023.csv',
 '02-12-2020.csv',
 '02-12-2021.csv',
 '02-12-2022.csv',
 '02-12-2023.csv',
 '02-13-2020.csv',
 '02-13-2021.csv',
 '02-13-2022.csv',
 '02-13-2023.csv',
 '02-14-2020.csv',
 '02-14-2021.csv',
 '02-14-2022.csv',
 '02-14-2023.csv',
 '02-15-2020.csv',
 '02-15-2021.csv',
 '02-15-2022.csv',
 '02-15-2023.csv',
 '02-16-2020.csv',
 '02-16-2021.csv',
 '02-16-2022.csv',
 '02-16-2023.csv',
 '02-17-2020.csv',
 '02-17-2021.csv',
 '02-17-2022.csv',
 '02-17-2023.csv',
 '02-18-2020.csv',
 '02-18-2021.csv',
 '02-18-2022.csv',
 '02-18-2023.csv',
 '02-19-2020.csv',
 '02-19-2021.csv',
 '02-19-2022.csv',
 '02-19-2023.csv',
 '02-20-2020.csv',
 '02-20-2021.csv',
 '02-20-2022.csv',
 '02-20-2023.csv',
 '02-21-2020.csv',
 '02-21-2021.csv',
 '02-21-2022.csv',
 '02-21-2023.csv',
 '02-22-2020.csv',
 '02-22-2021.csv',
 '02-22-2022.csv',
 '02-22-2023.csv',
 '02-23-2020.csv',
 '02-23-2021.csv',
 '02-23-2022.csv',
 '02-23-2023.csv',
 '02-24-2020.csv',
 '02-24-2021.csv',
 '02-24-2022.csv',
 '02-24-2023.csv',
 '02-25-2020.csv',
 '02-25-2021.csv',
 '02-25-2022.csv',
 '02-25-2023.csv',
 '02-26-2020.csv',
 '02-26-2021.csv',
 '02-26-2022.csv',
 '02-26-2023.csv',
 '02-27-2020.csv',
 '02-27-2021.csv',
 '02-27-2022.csv',
 '02-27-2023.csv',
 '02-28-2020.csv',
 '02-28-2021.csv',
 '02-28-2022.csv',
 '02-28-2023.csv',
 '02-29-2020.csv',
 '03-01-2020.csv',
 '03-01-2021.csv',
 '03-01-2022.csv',
 '03-01-2023.csv',
 '03-02-2020.csv',
 '03-02-2021.csv',
 '03-02-2022.csv',
 '03-02-2023.csv',
 '03-03-2020.csv',
 '03-03-2021.csv',
 '03-03-2022.csv',
 '03-03-2023.csv',
 '03-04-2020.csv',
 '03-04-2021.csv',
 '03-04-2022.csv',
 '03-04-2023.csv',
 '03-05-2020.csv',
 '03-05-2021.csv',
 '03-05-2022.csv',
 '03-05-2023.csv',
 '03-06-2020.csv',
 '03-06-2021.csv',
 '03-06-2022.csv',
 '03-06-2023.csv',
 '03-07-2020.csv',
 '03-07-2021.csv',
 '03-07-2022.csv',
 '03-07-2023.csv',
 '03-08-2020.csv',
 '03-08-2021.csv',
 '03-08-2022.csv',
 '03-08-2023.csv',
 '03-09-2020.csv',
 '03-09-2021.csv',
 '03-09-2022.csv',
 '03-09-2023.csv',
 '03-10-2020.csv',
 '03-10-2021.csv',
 '03-10-2022.csv',
 '03-11-2020.csv',
 '03-11-2021.csv',
 '03-11-2022.csv',
 '03-12-2020.csv',
 '03-12-2021.csv',
 '03-12-2022.csv',
 '03-13-2020.csv',
 '03-13-2021.csv',
 '03-13-2022.csv',
 '03-14-2020.csv',
 '03-14-2021.csv',
 '03-14-2022.csv',
 '03-15-2020.csv',
 '03-15-2021.csv',
 '03-15-2022.csv',
 '03-16-2020.csv',
 '03-16-2021.csv',
 '03-16-2022.csv',
 '03-17-2020.csv',
 '03-17-2021.csv',
 '03-17-2022.csv',
 '03-18-2020.csv',
 '03-18-2021.csv',
 '03-18-2022.csv',
 '03-19-2020.csv',
 '03-19-2021.csv',
 '03-19-2022.csv',
 '03-20-2020.csv',
 '03-20-2021.csv',
 '03-20-2022.csv',
 '03-21-2020.csv',
 '03-21-2021.csv',
 '03-21-2022.csv',
 '03-22-2020.csv',
 '03-22-2021.csv',
 '03-22-2022.csv',
 '03-23-2020.csv',
 '03-23-2021.csv',
 '03-23-2022.csv',
 '03-24-2020.csv',
 '03-24-2021.csv',
 '03-24-2022.csv',
 '03-25-2020.csv',
 '03-25-2021.csv',
 '03-25-2022.csv',
 '03-26-2020.csv',
 '03-26-2021.csv',
 '03-26-2022.csv',
 '03-27-2020.csv',
 '03-27-2021.csv',
 '03-27-2022.csv',
 '03-28-2020.csv',
 '03-28-2021.csv',
 '03-28-2022.csv',
 '03-29-2020.csv',
 '03-29-2021.csv',
 '03-29-2022.csv',
 '03-30-2020.csv',
 '03-30-2021.csv',
 '03-30-2022.csv',
 '03-31-2020.csv',
 '03-31-2021.csv',
 '03-31-2022.csv',
 '04-01-2020.csv',
 '04-01-2021.csv',
 '04-01-2022.csv',
 '04-02-2020.csv',
 '04-02-2021.csv',
 '04-02-2022.csv',
 '04-03-2020.csv',
 '04-03-2021.csv',
 '04-03-2022.csv',
 '04-04-2020.csv',
 '04-04-2021.csv',
 '04-04-2022.csv',
 '04-05-2020.csv',
 '04-05-2021.csv',
 '04-05-2022.csv',
 '04-06-2020.csv',
 '04-06-2021.csv',
 '04-06-2022.csv',
 '04-07-2020.csv',
 '04-07-2021.csv',
 '04-07-2022.csv',
 '04-08-2020.csv',
 '04-08-2021.csv',
 '04-08-2022.csv',
 '04-09-2020.csv',
 '04-09-2021.csv',
 '04-09-2022.csv',
 '04-10-2020.csv',
 '04-10-2021.csv',
 '04-10-2022.csv',
 '04-11-2020.csv',
 '04-11-2021.csv',
 '04-11-2022.csv',
 '04-12-2020.csv',
 '04-12-2021.csv',
 '04-12-2022.csv',
 '04-13-2020.csv',
 '04-13-2021.csv',
 '04-13-2022.csv',
 '04-14-2020.csv',
 '04-14-2021.csv',
 '04-14-2022.csv',
 '04-15-2020.csv',
 '04-15-2021.csv',
 '04-15-2022.csv',
 '04-16-2020.csv',
 '04-16-2021.csv',
 '04-16-2022.csv',
 '04-17-2020.csv',
 '04-17-2021.csv',
 '04-17-2022.csv',
 '04-18-2020.csv',
 '04-18-2021.csv',
 '04-18-2022.csv',
 '04-19-2020.csv',
 '04-19-2021.csv',
 '04-19-2022.csv',
 '04-20-2020.csv',
 '04-20-2021.csv',
 '04-20-2022.csv',
 '04-21-2020.csv',
 '04-21-2021.csv',
 '04-21-2022.csv',
 '04-22-2020.csv',
 '04-22-2021.csv',
 '04-22-2022.csv',
 '04-23-2020.csv',
 '04-23-2021.csv',
 '04-23-2022.csv',
 '04-24-2020.csv',
 '04-24-2021.csv',
 '04-24-2022.csv',
 '04-25-2020.csv',
 '04-25-2021.csv',
 '04-25-2022.csv',
 '04-26-2020.csv',
 '04-26-2021.csv',
 '04-26-2022.csv',
 '04-27-2020.csv',
 '04-27-2021.csv',
 '04-27-2022.csv',
 '04-28-2020.csv',
 '04-28-2021.csv',
 '04-28-2022.csv',
 '04-29-2020.csv',
 '04-29-2021.csv',
 '04-29-2022.csv',
 '04-30-2020.csv',
 '04-30-2021.csv',
 '04-30-2022.csv',
 '05-01-2020.csv',
 '05-01-2021.csv',
 '05-01-2022.csv',
 '05-02-2020.csv',
 '05-02-2021.csv',
 '05-02-2022.csv',
 '05-03-2020.csv',
 '05-03-2021.csv',
 '05-03-2022.csv',
 '05-04-2020.csv',
 '05-04-2021.csv',
 '05-04-2022.csv',
 '05-05-2020.csv',
 '05-05-2021.csv',
 '05-05-2022.csv',
 '05-06-2020.csv',
 '05-06-2021.csv',
 '05-06-2022.csv',
 '05-07-2020.csv',
 '05-07-2021.csv',
 '05-07-2022.csv',
 '05-08-2020.csv',
 '05-08-2021.csv',
 '05-08-2022.csv',
 '05-09-2020.csv',
 '05-09-2021.csv',
 '05-09-2022.csv',
 '05-10-2020.csv',
 '05-10-2021.csv',
 '05-10-2022.csv',
 '05-11-2020.csv',
 '05-11-2021.csv',
 '05-11-2022.csv',
 '05-12-2020.csv',
 '05-12-2021.csv',
 '05-12-2022.csv',
 '05-13-2020.csv',
 '05-13-2021.csv',
 '05-13-2022.csv',
 '05-14-2020.csv',
 '05-14-2021.csv',
 '05-14-2022.csv',
 '05-15-2020.csv',
 '05-15-2021.csv',
 '05-15-2022.csv',
 '05-16-2020.csv',
 '05-16-2021.csv',
 '05-16-2022.csv',
 '05-17-2020.csv',
 '05-17-2021.csv',
 '05-17-2022.csv',
 '05-18-2020.csv',
 '05-18-2021.csv',
 '05-18-2022.csv',
 '05-19-2020.csv',
 '05-19-2021.csv',
 '05-19-2022.csv',
 '05-20-2020.csv',
 '05-20-2021.csv',
 '05-20-2022.csv',
 '05-21-2020.csv',
 '05-21-2021.csv',
 '05-21-2022.csv',
 '05-22-2020.csv',
 '05-22-2021.csv',
 '05-22-2022.csv',
 '05-23-2020.csv',
 '05-23-2021.csv',
 '05-23-2022.csv',
 '05-24-2020.csv',
 '05-24-2021.csv',
 '05-24-2022.csv',
 '05-25-2020.csv',
 '05-25-2021.csv',
 '05-25-2022.csv',
 '05-26-2020.csv',
 '05-26-2021.csv',
 '05-26-2022.csv',
 '05-27-2020.csv',
 '05-27-2021.csv',
 '05-27-2022.csv',
 '05-28-2020.csv',
 '05-28-2021.csv',
 '05-28-2022.csv',
 '05-29-2020.csv',
 '05-29-2021.csv',
 '05-29-2022.csv',
 '05-30-2020.csv',
 '05-30-2021.csv',
 '05-30-2022.csv',
 '05-31-2020.csv',
 '05-31-2021.csv',
 '05-31-2022.csv',
 '06-01-2020.csv',
 '06-01-2021.csv',
 '06-01-2022.csv',
 '06-02-2020.csv',
 '06-02-2021.csv',
 '06-02-2022.csv',
 '06-03-2020.csv',
 '06-03-2021.csv',
 '06-03-2022.csv',
 '06-04-2020.csv',
 '06-04-2021.csv',
 '06-04-2022.csv',
 '06-05-2020.csv',
 '06-05-2021.csv',
 '06-05-2022.csv',
 '06-06-2020.csv',
 '06-06-2021.csv',
 '06-06-2022.csv',
 '06-07-2020.csv',
 '06-07-2021.csv',
 '06-07-2022.csv',
 '06-08-2020.csv',
 '06-08-2021.csv',
 '06-08-2022.csv',
 '06-09-2020.csv',
 '06-09-2021.csv',
 '06-09-2022.csv',
 '06-10-2020.csv',
 '06-10-2021.csv',
 '06-10-2022.csv',
 '06-11-2020.csv',
 '06-11-2021.csv',
 '06-11-2022.csv',
 '06-12-2020.csv',
 '06-12-2021.csv',
 '06-12-2022.csv',
 '06-13-2020.csv',
 '06-13-2021.csv',
 '06-13-2022.csv',
 '06-14-2020.csv',
 '06-14-2021.csv',
 '06-14-2022.csv',
 '06-15-2020.csv',
 '06-15-2021.csv',
 '06-15-2022.csv',
 '06-16-2020.csv',
 '06-16-2021.csv',
 '06-16-2022.csv',
 '06-17-2020.csv',
 '06-17-2021.csv',
 '06-17-2022.csv',
 '06-18-2020.csv',
 '06-18-2021.csv',
 '06-18-2022.csv',
 '06-19-2020.csv',
 '06-19-2021.csv',
 '06-19-2022.csv',
 '06-20-2020.csv',
 '06-20-2021.csv',
 '06-20-2022.csv',
 '06-21-2020.csv',
 '06-21-2021.csv',
 '06-21-2022.csv',
 '06-22-2020.csv',
 '06-22-2021.csv',
 '06-22-2022.csv',
 '06-23-2020.csv',
 '06-23-2021.csv',
 '06-23-2022.csv',
 '06-24-2020.csv',
 '06-24-2021.csv',
 '06-24-2022.csv',
 '06-25-2020.csv',
 '06-25-2021.csv',
 '06-25-2022.csv',
 '06-26-2020.csv',
 '06-26-2021.csv',
 '06-26-2022.csv',
 '06-27-2020.csv',
 '06-27-2021.csv',
 '06-27-2022.csv',
 '06-28-2020.csv',
 '06-28-2021.csv',
 '06-28-2022.csv',
 '06-29-2020.csv',
 '06-29-2021.csv',
 '06-29-2022.csv',
 '06-30-2020.csv',
 '06-30-2021.csv',
 '06-30-2022.csv',
 '07-01-2020.csv',
 '07-01-2021.csv',
 '07-01-2022.csv',
 '07-02-2020.csv',
 '07-02-2021.csv',
 '07-02-2022.csv',
 '07-03-2020.csv',
 '07-03-2021.csv',
 '07-03-2022.csv',
 '07-04-2020.csv',
 '07-04-2021.csv',
 '07-04-2022.csv',
 '07-05-2020.csv',
 '07-05-2021.csv',
 '07-05-2022.csv',
 '07-06-2020.csv',
 '07-06-2021.csv',
 '07-06-2022.csv',
 '07-07-2020.csv',
 '07-07-2021.csv',
 '07-07-2022.csv',
 '07-08-2020.csv',
 '07-08-2021.csv',
 '07-08-2022.csv',
 '07-09-2020.csv',
 '07-09-2021.csv',
 '07-09-2022.csv',
 '07-10-2020.csv',
 '07-10-2021.csv',
 '07-10-2022.csv',
 '07-11-2020.csv',
 '07-11-2021.csv',
 '07-11-2022.csv',
 '07-12-2020.csv',
 '07-12-2021.csv',
 '07-12-2022.csv',
 '07-13-2020.csv',
 '07-13-2021.csv',
 '07-13-2022.csv',
 '07-14-2020.csv',
 '07-14-2021.csv',
 '07-14-2022.csv',
 '07-15-2020.csv',
 '07-15-2021.csv',
 '07-15-2022.csv',
 '07-16-2020.csv',
 '07-16-2021.csv',
 '07-16-2022.csv',
 '07-17-2020.csv',
 '07-17-2021.csv',
 '07-17-2022.csv',
 '07-18-2020.csv',
 '07-18-2021.csv',
 '07-18-2022.csv',
 '07-19-2020.csv',
 '07-19-2021.csv',
 '07-19-2022.csv',
 '07-20-2020.csv',
 '07-20-2021.csv',
 '07-20-2022.csv',
 '07-21-2020.csv',
 '07-21-2021.csv',
 '07-21-2022.csv',
 '07-22-2020.csv',
 '07-22-2021.csv',
 '07-22-2022.csv',
 '07-23-2020.csv',
 '07-23-2021.csv',
 '07-23-2022.csv',
 '07-24-2020.csv',
 '07-24-2021.csv',
 '07-24-2022.csv',
 '07-25-2020.csv',
 '07-25-2021.csv',
 '07-25-2022.csv',
 '07-26-2020.csv',
 '07-26-2021.csv',
 '07-26-2022.csv',
 '07-27-2020.csv',
 '07-27-2021.csv',
 '07-27-2022.csv',
 '07-28-2020.csv',
 '07-28-2021.csv',
 '07-28-2022.csv',
 '07-29-2020.csv',
 '07-29-2021.csv',
 '07-29-2022.csv',
 '07-30-2020.csv',
 '07-30-2021.csv',
 '07-30-2022.csv',
 '07-31-2020.csv',
 '07-31-2021.csv',
 '07-31-2022.csv',
 '08-01-2020.csv',
 '08-01-2021.csv',
 '08-01-2022.csv',
 '08-02-2020.csv',
 '08-02-2021.csv',
 '08-02-2022.csv',
 '08-03-2020.csv',
 '08-03-2021.csv',
 '08-03-2022.csv',
 '08-04-2020.csv',
 '08-04-2021.csv',
 '08-04-2022.csv',
 '08-05-2020.csv',
 '08-05-2021.csv',
 '08-05-2022.csv',
 '08-06-2020.csv',
 '08-06-2021.csv',
 '08-06-2022.csv',
 '08-07-2020.csv',
 '08-07-2021.csv',
 '08-07-2022.csv',
 '08-08-2020.csv',
 '08-08-2021.csv',
 '08-08-2022.csv',
 '08-09-2020.csv',
 '08-09-2021.csv',
 '08-09-2022.csv',
 '08-10-2020.csv',
 '08-10-2021.csv',
 '08-10-2022.csv',
 '08-11-2020.csv',
 '08-11-2021.csv',
 '08-11-2022.csv',
 '08-12-2020.csv',
 '08-12-2021.csv',
 '08-12-2022.csv',
 '08-13-2020.csv',
 '08-13-2021.csv',
 '08-13-2022.csv',
 '08-14-2020.csv',
 '08-14-2021.csv',
 '08-14-2022.csv',
 '08-15-2020.csv',
 '08-15-2021.csv',
 '08-15-2022.csv',
 '08-16-2020.csv',
 '08-16-2021.csv',
 '08-16-2022.csv',
 '08-17-2020.csv',
 '08-17-2021.csv',
 '08-17-2022.csv',
 '08-18-2020.csv',
 '08-18-2021.csv',
 '08-18-2022.csv',
 '08-19-2020.csv',
 '08-19-2021.csv',
 '08-19-2022.csv',
 '08-20-2020.csv',
 '08-20-2021.csv',
 '08-20-2022.csv',
 '08-21-2020.csv',
 '08-21-2021.csv',
 '08-21-2022.csv',
 '08-22-2020.csv',
 '08-22-2021.csv',
 '08-22-2022.csv',
 '08-23-2020.csv',
 '08-23-2021.csv',
 '08-23-2022.csv',
 '08-24-2020.csv',
 '08-24-2021.csv',
 '08-24-2022.csv',
 '08-25-2020.csv',
 '08-25-2021.csv',
 '08-25-2022.csv',
 '08-26-2020.csv',
 '08-26-2021.csv',
 '08-26-2022.csv',
 '08-27-2020.csv',
 '08-27-2021.csv',
 '08-27-2022.csv',
 '08-28-2020.csv',
 '08-28-2021.csv',
 '08-28-2022.csv',
 '08-29-2020.csv',
 '08-29-2021.csv',
 '08-29-2022.csv',
 '08-30-2020.csv',
 '08-30-2021.csv',
 '08-30-2022.csv',
 '08-31-2020.csv',
 '08-31-2021.csv',
 '08-31-2022.csv',
 '09-01-2020.csv',
 '09-01-2021.csv',
 '09-01-2022.csv',
 '09-02-2020.csv',
 '09-02-2021.csv',
 '09-02-2022.csv',
 '09-03-2020.csv',
 '09-03-2021.csv',
 '09-03-2022.csv',
 '09-04-2020.csv',
 '09-04-2021.csv',
 '09-04-2022.csv',
 '09-05-2020.csv',
 '09-05-2021.csv',
 '09-05-2022.csv',
 '09-06-2020.csv',
 '09-06-2021.csv',
 '09-06-2022.csv',
 '09-07-2020.csv',
 '09-07-2021.csv',
 '09-07-2022.csv',
 '09-08-2020.csv',
 '09-08-2021.csv',
 '09-08-2022.csv',
 '09-09-2020.csv',
 '09-09-2021.csv',
 '09-09-2022.csv',
 '09-10-2020.csv',
 '09-10-2021.csv',
 '09-10-2022.csv',
 '09-11-2020.csv',
 '09-11-2021.csv',
 '09-11-2022.csv',
 '09-12-2020.csv',
 '09-12-2021.csv',
 '09-12-2022.csv',
 '09-13-2020.csv',
 '09-13-2021.csv',
 '09-13-2022.csv',
 '09-14-2020.csv',
 '09-14-2021.csv',
 '09-14-2022.csv',
 '09-15-2020.csv',
 '09-15-2021.csv',
 '09-15-2022.csv',
 '09-16-2020.csv',
 '09-16-2021.csv',
 '09-16-2022.csv',
 '09-17-2020.csv',
 '09-17-2021.csv',
 '09-17-2022.csv',
 '09-18-2020.csv',
 '09-18-2021.csv',
 '09-18-2022.csv',
 '09-19-2020.csv',
 '09-19-2021.csv',
 '09-19-2022.csv',
 '09-20-2020.csv',
 '09-20-2021.csv',
 '09-20-2022.csv',
 '09-21-2020.csv',
 '09-21-2021.csv',
 '09-21-2022.csv',
 '09-22-2020.csv',
 '09-22-2021.csv',
 '09-22-2022.csv',
 '09-23-2020.csv',
 '09-23-2021.csv',
 '09-23-2022.csv',
 '09-24-2020.csv',
 '09-24-2021.csv',
 '09-24-2022.csv',
 '09-25-2020.csv',
 '09-25-2021.csv',
 '09-25-2022.csv',
 '09-26-2020.csv',
 '09-26-2021.csv',
 '09-26-2022.csv',
 '09-27-2020.csv',
 '09-27-2021.csv',
 '09-27-2022.csv',
 '09-28-2020.csv',
 '09-28-2021.csv',
 '09-28-2022.csv',
 '09-29-2020.csv',
 '09-29-2021.csv',
 '09-29-2022.csv',
 '09-30-2020.csv',
 '09-30-2021.csv',
 '09-30-2022.csv',
 '10-01-2020.csv',
 '10-01-2021.csv',
 '10-01-2022.csv',
 '10-02-2020.csv',
 '10-02-2021.csv',
 '10-02-2022.csv',
 '10-03-2020.csv',
 '10-03-2021.csv',
 '10-03-2022.csv',
 '10-04-2020.csv',
 '10-04-2021.csv',
 '10-04-2022.csv',
 '10-05-2020.csv',
 '10-05-2021.csv',
 '10-05-2022.csv',
 '10-06-2020.csv',
 '10-06-2021.csv',
 '10-06-2022.csv',
 '10-07-2020.csv',
 '10-07-2021.csv',
 '10-07-2022.csv',
 '10-08-2020.csv',
 '10-08-2021.csv',
 '10-08-2022.csv',
 '10-09-2020.csv',
 '10-09-2021.csv',
 '10-09-2022.csv',
 '10-10-2020.csv',
 '10-10-2021.csv',
 '10-10-2022.csv',
 '10-11-2020.csv',
 '10-11-2021.csv',
 '10-11-2022.csv',
 '10-12-2020.csv',
 '10-12-2021.csv',
 '10-12-2022.csv',
 '10-13-2020.csv',
 '10-13-2021.csv',
 '10-13-2022.csv',
 '10-14-2020.csv',
 '10-14-2021.csv',
 '10-14-2022.csv',
 '10-15-2020.csv',
 '10-15-2021.csv',
 '10-15-2022.csv',
 '10-16-2020.csv',
 '10-16-2021.csv',
 '10-16-2022.csv',
 '10-17-2020.csv',
 '10-17-2021.csv',
 '10-17-2022.csv',
 '10-18-2020.csv',
 '10-18-2021.csv',
 '10-18-2022.csv',
 '10-19-2020.csv',
 '10-19-2021.csv',
 '10-19-2022.csv',
 '10-20-2020.csv',
 '10-20-2021.csv',
 '10-20-2022.csv',
 '10-21-2020.csv',
 '10-21-2021.csv',
 '10-21-2022.csv',
 '10-22-2020.csv',
 '10-22-2021.csv',
 '10-22-2022.csv',
 '10-23-2020.csv',
 '10-23-2021.csv',
 '10-23-2022.csv',
 '10-24-2020.csv',
 '10-24-2021.csv',
 '10-24-2022.csv',
 '10-25-2020.csv',
 '10-25-2021.csv',
 '10-25-2022.csv',
 '10-26-2020.csv',
 '10-26-2021.csv',
 '10-26-2022.csv',
 '10-27-2020.csv',
 '10-27-2021.csv',
 '10-27-2022.csv',
 '10-28-2020.csv',
 '10-28-2021.csv',
 '10-28-2022.csv',
 '10-29-2020.csv',
 '10-29-2021.csv',
 '10-29-2022.csv',
 '10-30-2020.csv',
 '10-30-2021.csv',
 '10-30-2022.csv',
 '10-31-2020.csv',
 '10-31-2021.csv',
 '10-31-2022.csv',
 '11-01-2020.csv',
 '11-01-2021.csv',
 '11-01-2022.csv',
 '11-02-2020.csv',
 '11-02-2021.csv',
 '11-02-2022.csv',
 '11-03-2020.csv',
 '11-03-2021.csv',
 '11-03-2022.csv',
 '11-04-2020.csv',
 '11-04-2021.csv',
 '11-04-2022.csv',
 '11-05-2020.csv',
 '11-05-2021.csv',
 '11-05-2022.csv',
 '11-06-2020.csv',
 '11-06-2021.csv',
 '11-06-2022.csv',
 '11-07-2020.csv',
 '11-07-2021.csv',
 '11-07-2022.csv',
 '11-08-2020.csv',
 '11-08-2021.csv',
 '11-08-2022.csv',
 '11-09-2020.csv',
 '11-09-2021.csv',
 '11-09-2022.csv',
 '11-10-2020.csv',
 '11-10-2021.csv',
 '11-10-2022.csv',
 '11-11-2020.csv',
 '11-11-2021.csv',
 '11-11-2022.csv',
 '11-12-2020.csv',
 '11-12-2021.csv',
 '11-12-2022.csv',
 '11-13-2020.csv',
 '11-13-2021.csv',
 '11-13-2022.csv',
 '11-14-2020.csv',
 ...]

# 최종 데이터 만들기

1. 필요한 컬럼만 가지고 있는 리스트 형태로 데이터 추출하기
2. 해당 데이터 정렬하기
3. 데이터 합치기

In [79]:
import pandas as pd
import json

with open("COVID-19-master/csse_covid_19_data/country_convert.json", "r", encoding="utf-8-sig") as json_file :
    json_data = json.load(json_file)

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"

def country_name_convert(row) :
    if row["Country_Region"] in json_data :
        return json_data[row["Country_Region"]]
    return row["Country_Region"]
    

def create_dataframe(filename) :
    doc = pd.read_csv(f"{PATH}{filename}", encoding="utf-8-sig")
    
    try :
        doc = doc[["Country_Region", "Confirmed"]]
    except :
        doc = doc[["Country/Region", "Confirmed"]]
        doc.columns = ["Country_Region", "Confirmed"]
    
    doc = doc.dropna(subset=["Confirmed"])
    doc["Country_Region"] = doc.apply(country_name_convert, axis=1)
    doc = doc.astype({"Confirmed": "int64"})
    doc = doc.groupby("Country_Region").sum()

    date_column = filename.split(".")[0].lstrip("0").replace("-", "/")
    doc.columns = [date_column]
    return doc

In [82]:
import os
from datetime import datetime

def generate_dataframe_by_path(PATH) :
    file_list, csv_list = os.listdir(PATH), list()
    first_doc = True
    
    for file in file_list :
        if file.split(".")[-1] == "csv" :
            csv_list.append(file)
    csv_list.sort(key=lambda x : datetime.strptime(x, "%m-%d-%Y.csv"))

    for file in csv_list :
        doc = create_dataframe(file)

        if first_doc :
            final_doc, first_doc = doc, False
        else :
            final_doc = pd.merge(final_doc, doc, how="outer", left_index=True, right_index=True)

    final_doc = final_doc.fillna(0)
    return final_doc
# 최초에 값이 들어오는 상황에서는 merge -> 최소한 2개의 필드가 존재, 2번째 부터는 이미 최초의 값이 들어왔기때문에 merge 사용가능

In [83]:
PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"

doc = generate_dataframe_by_path(PATH)
doc

,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,1/31/2020,...,2/28/2023,3/01/2023,3/02/2023,3/03/2023,3/04/2023,3/05/2023,3/06/2023,3/07/2023,3/08/2023,3/09/2023
Country_Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,209322.0,209340.0,209358.0,209362.0,209369.0,209390.0,209406.0,209436.0,209451.0,209451.0
Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,334391.0,334408.0,334408.0,334427.0,334427.0,334427.0,334427.0,334427.0,334443.0,334457.0
Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,271441.0,271448.0,271463.0,271469.0,271469.0,271477.0,271477.0,271490.0,271494.0,271496.0
Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,47866.0,47875.0,47875.0,47875.0,47875.0,47875.0,47875.0,47875.0,47890.0,47890.0
Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,105255.0,105277.0,105277.0,105277.0,105277.0,105277.0,105277.0,105277.0,105288.0,105288.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,703228.0,703228.0,703228.0,703228.0,703228.0,703228.0,703228.0,703228.0,703228.0,703228.0
Winter Olympics 2022,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,535.0,535.0,535.0,535.0,535.0,535.0,535.0,535.0,535.0,535.0
Yemen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11945.0,11945.0,11945.0,11945.0,11945.0,11945.0,11945.0,11945.0,11945.0,11945.0
Zambia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,343012.0,343012.0,343079.0,343079.0,343079.0,343135.0,343135.0,343135.0,343135.0,343135.0
Zimbabwe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,263921.0,264127.0,264127.0,264127.0,264127.0,264127.0,264127.0,264127.0,264276.0,264276.0

In [84]:
doc = doc.astype("int64")
doc

,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,1/31/2020,...,2/28/2023,3/01/2023,3/02/2023,3/03/2023,3/04/2023,3/05/2023,3/06/2023,3/07/2023,3/08/2023,3/09/2023
Country_Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,209322,209340,209358,209362,209369,209390,209406,209436,209451,209451
Albania,0,0,0,0,0,0,0,0,0,0,...,334391,334408,334408,334427,334427,334427,334427,334427,334443,334457
Algeria,0,0,0,0,0,0,0,0,0,0,...,271441,271448,271463,271469,271469,271477,271477,271490,271494,271496
Andorra,0,0,0,0,0,0,0,0,0,0,...,47866,47875,47875,47875,47875,47875,47875,47875,47890,47890
Angola,0,0,0,0,0,0,0,0,0,0,...,105255,105277,105277,105277,105277,105277,105277,105277,105288,105288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza,0,0,0,0,0,0,0,0,0,0,...,703228,703228,703228,703228,703228,703228,703228,703228,703228,703228
Winter Olympics 2022,0,0,0,0,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,535
Yemen,0,0,0,0,0,0,0,0,0,0,...,11945,11945,11945,11945,11945,11945,11945,11945,11945,11945
Zambia,0,0,0,0,0,0,0,0,0,0,...,343012,343012,343079,343079,343079,343135,343135,343135,343135,343135
Zimbabwe,0,0,0,0,0,0,0,0,0,0,...,263921,264127,264127,264127,264127,264127,264127,264127,264276,264276

In [85]:
doc.to_csv("COVID-19-master/final_df.csv")