In [1]:
import pandas as pd

# { } -> 딕셔너리, [ ] -> 리스트
df = pd.DataFrame({
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]
})

In [2]:
df

    미국    한국  중국
0  2.1  0.40  10
1  2.2  0.50  13
2  2.3  0.45  15

In [6]:
# 인덱스명이 변경된 것처럼 보이지만, 인덱스의 오리지널은 결국 0부터 1씩 증가하는 속성!!

df = pd.DataFrame({
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15],
},index=[2000, 2010, 2020])

In [5]:
df

       미국    한국  중국
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [7]:
df.index

Index([2000, 2010, 2020], dtype='int64')

In [8]:
df.index = [2001, 2002, 2003]

In [9]:
df

       미국    한국  중국
2001  2.1  0.40  10
2002  2.2  0.50  13
2003  2.3  0.45  15

In [10]:
df.columns

Index(['미국', '한국', '중국'], dtype='object')

In [11]:
df.columns = ["일본", "필리핀", "러시아"]

In [12]:
df

       일본   필리핀  러시아
2001  2.1  0.40   10
2002  2.2  0.50   13
2003  2.3  0.45   15

In [13]:
df.values

array([[ 2.1 ,  0.4 , 10.  ],
       [ 2.2 ,  0.5 , 13.  ],
       [ 2.3 ,  0.45, 15.  ]])

In [14]:
df = pd.DataFrame({
    "년도": [2000, 2010, 2020],
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]
})

In [15]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [17]:
df.set_index("년도")

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [19]:
df = df.set_index("년도")

In [20]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [21]:
df.reset_index("년도")

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [22]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [23]:
df = df.reset_index("년도")

In [24]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [25]:
df = df.set_index("년도")

In [26]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [28]:
df.index.name

'년도'

In [29]:
df.index.name = "연도"

In [30]:
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [31]:
df = df.reset_index("연도")

In [32]:
df

     연도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [33]:
df = df.set_index("연도")
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [34]:
df.loc[2000]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [35]:
df.iloc[0]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [36]:
type(df.loc[2000])

pandas.core.series.Series

In [37]:
df["미국"]

연도
2000    2.1
2010    2.2
2020    2.3
Name: 미국, dtype: float64

In [38]:
type(df["미국"])

pandas.core.series.Series

In [42]:
print(df["미국"][2000])
print(df.loc[2000]["미국"])
print(df.iloc[0]["미국"])

2.1
2.1
2.1

In [43]:
df = pd.DataFrame({
    "년도": ["2000", "2010", "2020"],
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]
})

df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [44]:
df = df.set_index("년도")
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [46]:
df.loc["2000"]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [47]:
df.index

Index(['2000', '2010', '2020'], dtype='object', name='년도')

In [48]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [49]:
df.columns

Index(['미국', '한국', '중국'], dtype='object')

In [50]:
df["일본"] = [1, 2, 3]

In [51]:
df

       미국    한국  중국  일본
년도
2000  2.1  0.40  10   1
2010  2.2  0.50  13   2
2020  2.3  0.45  15   3

In [52]:
del df["일본"]

In [53]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [54]:
df.loc["2021"] = [1, 2, 3]

In [55]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15
2021  1.0  2.00   3

In [56]:
df.drop(["2021"])

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [57]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15
2021  1.0  2.00   3

In [58]:
df = df.drop(["2021"])

In [59]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [60]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [61]:
df = df.reset_index("년도")
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [64]:
df2 = df[["한국", "중국"]].copy()

In [65]:
df2

     한국  중국
0  0.40  10
1  0.50  13
2  0.45  15

In [66]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [68]:
df2.columns

Index(['한국', '중국'], dtype='object')

In [69]:
df2.columns = ["브라질", "아르헨티나"]

In [70]:
df2

    브라질  아르헨티나
0  0.40     10
1  0.50     13
2  0.45     15

In [71]:
df2["년도"] = [2000, 2010, 2020]

In [72]:
df2

    브라질  아르헨티나    년도
0  0.40     10  2000
1  0.50     13  2010
2  0.45     15  2020

In [73]:
df2 = df2.set_index("년도")

In [74]:
df2

       브라질  아르헨티나
년도
2000  0.40     10
2010  0.50     13
2020  0.45     15

In [75]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [76]:
# 깊은복사, 얕은복사 => stack, que, deque => C/S
# 파이썬 x // 모르는 문법 (데이터)